--- @enum ow.ControlIndicatorType
ow.ControlIndicatorType = {
    MOTION_NON_BUBBLE = "MOTION_NON_BUBBLE",
    MOTION_BUBBLE = "MOTION_BUBBLE",
    INTERACT = "INTERACT",
    SLIDE_FREELY = "SLIDE_FREELY",
    MID_AIR_HOLD_DOWN_TO_ACCELERATRE = "MID_AIR_HOLD_DOWN_TO_ACCELERATE",
    ACCELERATOR_SURFACE_VERTICAL = "ACCELERATOR_SURFACE_VERTICAL",
    ACCELERATOR_SURFACE_HORIZONTAL = "ACCELERATOR_SURFACE_HORIZONTAL",
    ACCELERATOR_SURFACE_GENERAL = "ACCELERATOR_SURFACE_GENERAL",
    DIALOG_ADVANCE = "DIALOG_ADVANCE",
    DIALOG_SKIP = "DIALOG_SKIP",
    DIALOG_EXIT = "DIALOG_EXIT",
    DIALOG_SELECT_OPTION = "DIALOG_SELECT_OPTION",
    AIR_DASH = "AIR_DASH",
    DOUBLE_JUMP = "DOUBLE_JUMP",
    OMNIDIRECTIONAL_MOVEMENT = "OMNIDIRECTIONAL_MOVEMENT",
    NONE = "NONE"
}
ow.ControlIndicatorType = meta.enum("ControlIndicatorType", ow.ControlIndicatorType)
