b2.Vec2 = ffi.metatype("b2Vec2", {})
b2.Rot = ffi.metatype("b2Rot", {})
b2.Transform = ffi.metatype("b2Transform", {})
b2.AABB = ffi.metatype("b2AABB", {})
b2.IdentityTransform = b2.Transform(b2.Vec2(0, 0), b2.Rot(1, 0))
