return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 631,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 541,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -4640,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 848 },
            { x = 3600, y = 848 },
            { x = 3600, y = -16 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -3248,
          y = 1328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 80, y = 32 },
            { x = 1024, y = 32 },
            { x = 1024, y = -720 },
            { x = 80, y = -720 }
          },
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -1040,
          y = 1392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -368, y = 0 },
            { x = -368, y = -1152 },
            { x = 0, y = -1152 }
          },
          properties = {}
        },
        {
          id = 621,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -1712,
          y = -864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 896, y = 0 },
            { x = 896, y = 800 },
            { x = 0, y = 800 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "back",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 540,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -4128,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -32 },
            { x = -32, y = 416 },
            { x = 400, y = 416 },
            { x = 400, y = -32 },
            { x = 176, y = -240 }
          },
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -3184,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -208 },
            { x = 32, y = -208 },
            { x = 32, y = -304 },
            { x = 0, y = -304 },
            { x = 0, y = -608 },
            { x = 960, y = -608 },
            { x = 960, y = 0 }
          },
          properties = {
            ["type"] = "spheres"
          }
        },
        {
          id = 622,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1712,
          y = -864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 896, y = 0 },
            { x = 896, y = 800 },
            { x = 0, y = 800 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 341,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -1992.21,
          y = 904.104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 358,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -4496,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 0 },
            { x = 528, y = 0 },
            { x = 528, y = -288 },
            { x = 512, y = -288 },
            { x = 544, y = -336 },
            { x = 576, y = -288 },
            { x = 560, y = -288 },
            { x = 560, y = 0 },
            { x = 1200, y = 0 },
            { x = 1200, y = -64 },
            { x = 1264, y = -64 },
            { x = 1264, y = 0 },
            { x = 3280, y = 0 },
            { x = 3280, y = -1104 },
            { x = 3520, y = -1104 },
            { x = 3520, y = -352 },
            { x = 3520, y = 0 },
            { x = 3376, y = 0 },
            { x = 3376, y = -352 },
            { x = 3408, y = -352 },
            { x = 3360, y = -416 },
            { x = 3312, y = -352 },
            { x = 3344, y = -352 },
            { x = 3344, y = 0 },
            { x = 3568, y = 0 },
            { x = 3584, y = 160 },
            { x = -272, y = 160 },
            { x = -272, y = -768 },
            { x = -112, y = -768 }
          },
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -4016,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -224 },
            { x = -16, y = -224 },
            { x = -16, y = -400 },
            { x = 0, y = -384 },
            { x = 128, y = -384 },
            { x = 144, y = -400 },
            { x = 144, y = -224 },
            { x = 128, y = -224 },
            { x = 128, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = -288 },
            { x = 96, y = -288 },
            { x = 64, y = -336 },
            { x = 32, y = -288 },
            { x = 48, y = -288 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -4032,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -3888,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -4032,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 160, y = 0 },
            { x = 144, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -4640,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = 48 },
            { x = 32, y = 816 },
            { x = 64, y = 816 },
            { x = 48, y = 800 },
            { x = 48, y = 48 }
          },
          properties = {}
        },
        {
          id = 539,
          name = "Flies",
          type = "Fireflies",
          shape = "point",
          x = -3952,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = 5
          }
        },
        {
          id = 542,
          name = "NPC tangential",
          type = "NPC",
          shape = "point",
          x = -4528,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "accelerator_tutorial_press_tangential"
          }
        },
        {
          id = 549,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2512,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -208, y = 0 },
            { x = -208, y = 16 },
            { x = -672, y = 16 },
            { x = -672, y = -144 },
            { x = -640, y = -144 },
            { x = -640, y = -96 },
            { x = -627.164, y = -58.5404 },
            { x = -606.019, y = -32.7977 },
            { x = -567.666, y = -10.9191 },
            { x = -512, y = 0 },
            { x = -448, y = 0 }
          },
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3184,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -48 },
            { x = 32, y = -48 },
            { x = 32, y = -96 },
            { x = -48, y = -96 },
            { x = -48, y = 112 },
            { x = 0, y = 112 }
          },
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2928,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 208, y = 16 },
            { x = 672, y = 16 },
            { x = 672, y = -144 },
            { x = 640, y = -144 },
            { x = 640, y = -96 },
            { x = 627.164, y = -58.5404 },
            { x = 606.019, y = -32.7977 },
            { x = 567.666, y = -10.9191 },
            { x = 512, y = 0 },
            { x = 448, y = 0 }
          },
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2208,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -304 },
            { x = -16, y = -336 },
            { x = -48, y = -304 },
            { x = -48, y = -112 },
            { x = -80, y = -80 },
            { x = -80, y = -48 },
            { x = -48, y = -48 },
            { x = -48, y = 112 },
            { x = 16, y = 112 },
            { x = 16, y = -48 },
            { x = 48, y = -48 },
            { x = 48, y = -80 },
            { x = 16, y = -112 }
          },
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3184,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 992, y = -592 },
            { x = 992, y = -64 },
            { x = 32, y = -63.9509 },
            { x = 32, y = -16 },
            { x = 0, y = -16 },
            { x = 0, y = 160 },
            { x = 32, y = 160 },
            { x = 32, y = 208 },
            { x = -48, y = 208 },
            { x = -48, y = -592 }
          },
          properties = {}
        },
        {
          id = 560,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -3136,
          y = 752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -3152,
          y = 768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 0, y = 192 },
            { x = -32, y = 192 },
            { x = -32, y = 16 }
          },
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2208,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 960, y = 112 },
            { x = 960, y = -32 },
            { x = 752, y = -32 },
            { x = 528, y = 80 },
            { x = 528, y = 112 }
          },
          properties = {}
        },
        {
          id = 569,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1520,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -192, y = -16 },
            { x = -160, y = -16 },
            { x = -160, y = 16 },
            { x = -672, y = 16 },
            { x = -672, y = -144 },
            { x = -640, y = -144 },
            { x = -640, y = -96 },
            { x = -627.164, y = -58.5404 },
            { x = -606.019, y = -32.7977 },
            { x = -567.666, y = -10.9191 },
            { x = -512, y = 0 },
            { x = -448, y = 0 },
            { x = -240, y = 0 }
          },
          properties = {}
        },
        {
          id = 572,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1120,
          y = 688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 272, y = -1424 },
            { x = 272, y = -864 },
            { x = 268.94, y = -845.763 },
            { x = 261.127, y = -828.409 },
            { x = 249.654, y = -810.788 },
            { x = 235.043, y = -800.59 },
            { x = 216.878, y = -790.434 },
            { x = 192, y = -784 },
            { x = -96, y = -784 },
            { x = -96, y = -752 },
            { x = 304, y = -752 },
            { x = 304, y = -1424 }
          },
          properties = {}
        },
        {
          id = 574,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1312,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 128 },
            { x = 32, y = 128 },
            { x = 32, y = 208 },
            { x = 0, y = 192 },
            { x = 0, y = 160 },
            { x = -880, y = 160 },
            { x = -880, y = -192 },
            { x = 0, y = -192 }
          },
          properties = {}
        },
        {
          id = 575,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -1280,
          y = -96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 48 },
            { x = 32, y = 48 },
            { x = 32, y = 0 }
          },
          properties = {
            ["axis_y"] = 1
          }
        },
        {
          id = 579,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1216,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -752 },
            { x = -32, y = 354.504 },
            { x = -34.8787, y = 388.571 },
            { x = -38.3005, y = 415.175 },
            { x = -49.4977, y = 436.809 },
            { x = -62.1346, y = 458.538 },
            { x = -77.5558, y = 479.683 },
            { x = -104.849, y = 498.77 },
            { x = -144, y = 512 },
            { x = -32, y = 512 },
            { x = -32, y = 656 },
            { x = 0, y = 656 },
            { x = 0, y = -752 }
          },
          properties = {}
        },
        {
          id = 580,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1280,
          y = -96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 0 },
            { x = -32, y = 624 },
            { x = 0, y = 624 }
          },
          properties = {}
        },
        {
          id = 609,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -4032,
          y = -544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = false,
          polygon = {
            { x = 0, y = 16 },
            { x = 0, y = -448 },
            { x = 1632, y = -448 },
            { x = 1632, y = 16 }
          },
          properties = {}
        },
        {
          id = 613,
          name = "Fluid",
          type = "Fluid",
          shape = "point",
          x = -4400,
          y = 1072,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["bounds"] = { id = 614 }
          }
        },
        {
          id = 614,
          name = "",
          type = "FluidBounds",
          shape = "polygon",
          x = -4160,
          y = 864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -432, y = 0 },
            { x = -432, y = 432 },
            { x = -416, y = 448 },
            { x = 0, y = 448 }
          },
          properties = {}
        },
        {
          id = 618,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -64,
          y = -560,
          width = 0,
          height = 0,
          rotation = -90,
          visible = true,
          polygon = {
            { x = 272, y = -1200 },
            { x = 272, y = -864 },
            { x = 268.94, y = -845.763 },
            { x = 261.127, y = -828.409 },
            { x = 249.654, y = -810.788 },
            { x = 235.043, y = -800.59 },
            { x = 216.878, y = -790.434 },
            { x = 192, y = -784 },
            { x = 176, y = -784 },
            { x = 176, y = -752 },
            { x = 304, y = -752 },
            { x = 304, y = -1200 }
          },
          properties = {}
        },
        {
          id = 619,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1408,
          y = 688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -272, y = -880 },
            { x = -272, y = -864 },
            { x = -268.94, y = -845.763 },
            { x = -261.127, y = -828.409 },
            { x = -249.654, y = -810.788 },
            { x = -235.043, y = -800.59 },
            { x = -216.878, y = -790.434 },
            { x = -192, y = -784 },
            { x = 96, y = -784 },
            { x = 96, y = -752 },
            { x = -304, y = -752 },
            { x = -304, y = -880 }
          },
          properties = {}
        },
        {
          id = 620,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2464,
          y = -560,
          width = 0,
          height = 0,
          rotation = 90,
          visible = true,
          polygon = {
            { x = -272, y = -1200 },
            { x = -272, y = -864 },
            { x = -268.94, y = -845.763 },
            { x = -261.127, y = -828.409 },
            { x = -249.654, y = -810.788 },
            { x = -235.043, y = -800.59 },
            { x = -216.878, y = -790.434 },
            { x = -192, y = -784 },
            { x = 368, y = -784 },
            { x = 368, y = -752 },
            { x = -304, y = -752 },
            { x = -304, y = -1200 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 554,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -3152,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 556 }
          }
        },
        {
          id = 556,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -3152,
          y = 1104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 576,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -1280,
          y = -96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 577 }
          }
        },
        {
          id = 577,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -1248,
          y = -96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 623,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1264,
          y = -656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 64, y = 32 },
            { x = 32, y = 80 },
            { x = -32, y = 80 },
            { x = -64, y = 32 }
          },
          properties = {}
        },
        {
          id = 624,
          name = "",
          type = "Portal",
          shape = "point",
          x = -1328,
          y = -624,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 625 },
            ["target"] = { id = 626 }
          }
        },
        {
          id = 625,
          name = "",
          type = "PortalNode",
          shape = "point",
          x = -1200,
          y = -624,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 626,
          name = "",
          type = "Portal",
          shape = "point",
          x = -1312,
          y = -976,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 627 }
          }
        },
        {
          id = 627,
          name = "",
          type = "PortalNode",
          shape = "point",
          x = -1232,
          y = -976,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 628,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1328,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 48 },
            { x = -384, y = 48 },
            { x = -384, y = 160 },
            { x = 512, y = 160 },
            { x = 512, y = 48 },
            { x = 144, y = 48 },
            { x = 112, y = 0 },
            { x = 96, y = 0 },
            { x = 96, y = 48 },
            { x = 16, y = 48 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 629,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -1328,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 630 }
          }
        },
        {
          id = 630,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -1216,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
