return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 572,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 541,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -4640,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 848 },
            { x = 3600, y = 848 },
            { x = 3600, y = -16 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -3248,
          y = 1328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 80, y = 32 },
            { x = 1024, y = 32 },
            { x = 1024, y = -720 },
            { x = 80, y = -720 }
          },
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "",
          shape = "polygon",
          x = -1040,
          y = 1392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -368, y = 0 },
            { x = -368, y = -1152 },
            { x = 0, y = -1152 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "back",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 540,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -4128,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -32 },
            { x = -32, y = 416 },
            { x = 400, y = 416 },
            { x = 400, y = -32 },
            { x = 176, y = -240 }
          },
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -3184,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -208 },
            { x = 32, y = -208 },
            { x = 32, y = -304 },
            { x = 0, y = -304 },
            { x = 0, y = -608 },
            { x = 960, y = -608 },
            { x = 960, y = 0 }
          },
          properties = {
            ["type"] = "spheres"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 341,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -3371.5,
          y = 1165.08,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 358,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -4496,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 0 },
            { x = 528, y = 0 },
            { x = 528, y = -288 },
            { x = 512, y = -288 },
            { x = 544, y = -336 },
            { x = 576, y = -288 },
            { x = 560, y = -288 },
            { x = 560, y = 0 },
            { x = 1200, y = 0 },
            { x = 1200, y = -64 },
            { x = 1264, y = -64 },
            { x = 1264, y = 0 },
            { x = 3248, y = 0 },
            { x = 3248, y = -656 },
            { x = 3520, y = -656 },
            { x = 3520, y = -352 },
            { x = 3520, y = 0 },
            { x = 3376, y = 0 },
            { x = 3376, y = -352 },
            { x = 3408, y = -352 },
            { x = 3360, y = -416 },
            { x = 3312, y = -352 },
            { x = 3344, y = -352 },
            { x = 3344, y = 0 },
            { x = 3568, y = 0 },
            { x = 3584, y = 160 },
            { x = -272, y = 160 },
            { x = -272, y = -768 },
            { x = -112, y = -768 }
          },
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -4016,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -224 },
            { x = -16, y = -224 },
            { x = -16, y = -400 },
            { x = 0, y = -384 },
            { x = 128, y = -384 },
            { x = 144, y = -400 },
            { x = 144, y = -224 },
            { x = 128, y = -224 },
            { x = 128, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = -288 },
            { x = 96, y = -288 },
            { x = 64, y = -336 },
            { x = 32, y = -288 },
            { x = 48, y = -288 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -4032,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -3888,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -4032,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 160, y = 0 },
            { x = 144, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -4640,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = 48 },
            { x = 32, y = 816 },
            { x = 64, y = 816 },
            { x = 48, y = 800 },
            { x = 48, y = 48 }
          },
          properties = {}
        },
        {
          id = 539,
          name = "Flies",
          type = "Fireflies",
          shape = "point",
          x = -3952,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = 5
          }
        },
        {
          id = 542,
          name = "NPC tangential",
          type = "NPC",
          shape = "point",
          x = -4528,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "s"
          }
        },
        {
          id = 549,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2512,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -208, y = 0 },
            { x = -208, y = 16 },
            { x = -672, y = 16 },
            { x = -672, y = -144 },
            { x = -640, y = -144 },
            { x = -640, y = -96 },
            { x = -627.164, y = -58.5404 },
            { x = -606.019, y = -32.7977 },
            { x = -567.666, y = -10.9191 },
            { x = -512, y = 0 },
            { x = -448, y = 0 }
          },
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3184,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -48 },
            { x = 32, y = -48 },
            { x = 32, y = -96 },
            { x = -48, y = -96 },
            { x = -48, y = 112 },
            { x = 0, y = 112 }
          },
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2928,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 208, y = 16 },
            { x = 672, y = 16 },
            { x = 672, y = -144 },
            { x = 640, y = -144 },
            { x = 640, y = -96 },
            { x = 627.164, y = -58.5404 },
            { x = 606.019, y = -32.7977 },
            { x = 567.666, y = -10.9191 },
            { x = 512, y = 0 },
            { x = 448, y = 0 }
          },
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2208,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -304 },
            { x = -16, y = -336 },
            { x = -48, y = -304 },
            { x = -48, y = -112 },
            { x = -80, y = -80 },
            { x = -80, y = -48 },
            { x = -48, y = -48 },
            { x = -48, y = 112 },
            { x = 16, y = 112 },
            { x = 16, y = -48 },
            { x = 48, y = -48 },
            { x = 48, y = -80 },
            { x = 16, y = -112 }
          },
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3184,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 992, y = -592 },
            { x = 992, y = -64 },
            { x = 32, y = -63.9509 },
            { x = 32, y = -16 },
            { x = 0, y = -16 },
            { x = 0, y = 160 },
            { x = 32, y = 160 },
            { x = 32, y = 208 },
            { x = -48, y = 208 },
            { x = -48, y = -592 }
          },
          properties = {}
        },
        {
          id = 560,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -3136,
          y = 752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -3152,
          y = 768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 0, y = 192 },
            { x = -32, y = 192 },
            { x = -32, y = 16 }
          },
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2208,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 960, y = 112 },
            { x = 960, y = -32 },
            { x = 752, y = -32 },
            { x = 528, y = 80 },
            { x = 528, y = 112 }
          },
          properties = {}
        },
        {
          id = 569,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1520,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -192, y = -16 },
            { x = -160, y = -16 },
            { x = -160, y = 16 },
            { x = -672, y = 16 },
            { x = -672, y = -144 },
            { x = -640, y = -144 },
            { x = -640, y = -96 },
            { x = -627.164, y = -58.5404 },
            { x = -606.019, y = -32.7977 },
            { x = -567.666, y = -10.9191 },
            { x = -512, y = 0 },
            { x = -448, y = 0 },
            { x = -240, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 554,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -3152,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 556 }
          }
        },
        {
          id = 556,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -3152,
          y = 1104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
