return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 393,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 375,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -1168,
          y = 2240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "Bounds",
          type = "CameraBounds",
          shape = "rectangle",
          x = -4930.76,
          y = 1696,
          width = 6954.54,
          height = 1234.08,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "Bounds",
          type = "CameraBounds",
          shape = "rectangle",
          x = 900.556,
          y = 1696,
          width = 2363.44,
          height = 2976,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 339,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -960,
          y = 1440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 320 },
            { x = 3040, y = 320 },
            { x = 3040, y = 48 },
            { x = 1312, y = 56.9325 },
            { x = 1312, y = -656 },
            { x = 1056, y = -656 },
            { x = 1056, y = 16 },
            { x = 176, y = 16 },
            { x = 176, y = 0 }
          },
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = 96,
          y = 416,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 368 },
            { x = 384, y = 368 },
            { x = 384, y = 352 },
            { x = -16, y = 352 },
            { x = -16, y = 1024 },
            { x = -880, y = 1024 },
            { x = -880, y = 1040 },
            { x = 0, y = 1040 }
          },
          properties = {}
        },
        {
          id = 341,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -3168,
          y = 2496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -960,
          y = 1440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -80, y = -16 },
            { x = -128, y = -32 },
            { x = -160, y = -48 },
            { x = -192, y = -64 },
            { x = -229.931, y = -91.5519 },
            { x = -260.448, y = -122.811 },
            { x = -288, y = -160 },
            { x = -304, y = -192 },
            { x = -326.525, y = -240.275 },
            { x = -345.431, y = -299.574 },
            { x = -353.146, y = -338.412 },
            { x = -353.791, y = -385.699 },
            { x = -352.265, y = -419.84 },
            { x = -346.103, y = -457.78 },
            { x = -325.92, y = -522.172 },
            { x = -300.932, y = -570.226 },
            { x = -249.995, y = -636.54 },
            { x = -205.786, y = -677.866 },
            { x = -151.965, y = -711.504 },
            { x = -81.8068, y = -738.414 },
            { x = -10.6872, y = -752.83 },
            { x = 57.5493, y = -752.83 },
            { x = 2544, y = -752 },
            { x = 2587.54, y = -747.222 },
            { x = 2634.11, y = -733.513 },
            { x = 2665, y = -711.839 },
            { x = 2680.61, y = -682.955 },
            { x = 2695.84, y = -655.094 },
            { x = 2708.07, y = -623.863 },
            { x = 2714.75, y = -589.345 },
            { x = 2720, y = -544 },
            { x = 2720, y = -480 },
            { x = 2722.2, y = -160.764 },
            { x = 2712.31, y = -112.45 },
            { x = 2704, y = -80 },
            { x = 2689.73, y = -51.2942 },
            { x = 2661.7, y = -27.775 },
            { x = 2615.54, y = -14.9019 },
            { x = 2511.22, y = -15.3647 },
            { x = 2462.47, y = -21.0334 },
            { x = 2441.32, y = -39.3277 },
            { x = 2418.76, y = -77.9608 },
            { x = 2410.18, y = -125.531 },
            { x = 2404.48, y = -174.634 },
            { x = 2397.66, y = -210.785 },
            { x = 2384, y = -352 },
            { x = 2384, y = -661.507 },
            { x = 2383.18, y = -672.512 },
            { x = 2377.61, y = -682.326 },
            { x = 2368, y = -688 },
            { x = 1936, y = -688 },
            { x = 1936, y = -656 },
            { x = 2304, y = -656 },
            { x = 2368, y = -656 },
            { x = 2368, y = 32 },
            { x = 3056, y = 32 },
            { x = 3056, y = -784 },
            { x = -384, y = -784 },
            { x = -384, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        },
        {
          id = 345,
          name = "From",
          type = "Path",
          shape = "point",
          x = 432,
          y = 1347.92,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["next"] = { id = 346 },
            ["target"] = { id = 348 }
          }
        },
        {
          id = 346,
          name = "To",
          type = "PathNode",
          shape = "point",
          x = 720,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["easing"] = "LINEAR",
            ["velocity"] = 3
          }
        },
        {
          id = 348,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = 368,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = 320, y = 64 },
            { x = 320, y = 0 }
          },
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -3584,
          y = 2560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 336, y = 0 },
            { x = 656, y = 0 },
            { x = 656, y = 32 },
            { x = 1760, y = 32 },
            { x = 1776, y = 16 },
            { x = 1776, y = 368 },
            { x = 336, y = 368 }
          },
          properties = {}
        },
        {
          id = 352,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2928,
          y = 2560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 1104, y = 32 },
            { x = 1136, y = 0 },
            { x = 1136, y = -96 },
            { x = 1111.85, y = -90.5502 },
            { x = 1081.2, y = -73.877 },
            { x = 1049.27, y = -57.2503 },
            { x = 1011.54, y = -37.4894 },
            { x = 973.465, y = -23.5897 },
            { x = 939.412, y = -14.0388 },
            { x = 902.185, y = -5.18373 },
            { x = 867.215, y = 0 }
          },
          properties = {}
        },
        {
          id = 358,
          name = "",
          type = "",
          shape = "polygon",
          x = -3568,
          y = 3968,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 528, y = 0 },
            { x = 528, y = -288 },
            { x = 512, y = -288 },
            { x = 544, y = -336 },
            { x = 576, y = -288 },
            { x = 560, y = -288 },
            { x = 560, y = 0 },
            { x = 1280, y = 0 },
            { x = 1280, y = 160 },
            { x = 0, y = 160 }
          },
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3088,
          y = 3968,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -224 },
            { x = -16, y = -224 },
            { x = -16, y = -400 },
            { x = 0, y = -384 },
            { x = 128, y = -384 },
            { x = 144, y = -400 },
            { x = 144, y = -224 },
            { x = 128, y = -224 },
            { x = 128, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = -288 },
            { x = 96, y = -288 },
            { x = 64, y = -336 },
            { x = 32, y = -288 },
            { x = 48, y = -288 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -3104,
          y = 3664,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -2960,
          y = 3664,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 0, y = 304 },
            { x = 16, y = 304 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 362,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -3024,
          y = 3280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "",
          shape = "polygon",
          x = -3104,
          y = 3568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 160, y = 0 },
            { x = 144, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 368,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1792,
          y = 2560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 368 },
            { x = 0, y = 368 }
          },
          properties = {}
        },
        {
          id = 369,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1152,
          y = 2576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -48 },
            { x = -32, y = 352 },
            { x = -16, y = 352 },
            { x = -16, y = 0 },
            { x = 0, y = -16 },
            { x = 0, y = -48 }
          },
          properties = {}
        },
        {
          id = 374,
          name = "",
          type = "",
          shape = "polygon",
          x = -1184,
          y = 2528,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 48 },
            { x = 16, y = 48 },
            { x = 32, y = 32 },
            { x = 1232, y = 32 },
            { x = 1248, y = 32 },
            { x = 1440, y = 32 },
            { x = 1440, y = 400 },
            { x = 16, y = 400 }
          },
          properties = {}
        },
        {
          id = 384,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -1120,
          y = 2528,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 0 },
            { x = -32, y = 32 },
            { x = 1184, y = 32 },
            { x = 1184, y = 0 },
            { x = 1184, y = -144 },
            { x = 1184, y = -160 },
            { x = 1168, y = -160 },
            { x = 1104, y = -144 },
            { x = 960, y = -96 },
            { x = 704, y = -32 },
            { x = 416, y = 0 }
          },
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 64,
          y = 2368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 192 },
            { x = 192, y = 192 },
            { x = 192, y = 560 },
            { x = 208, y = 560 },
            { x = 208, y = 160 },
            { x = 208, y = 0 }
          },
          properties = {}
        },
        {
          id = 386,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 784,
          y = 2368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 160 },
            { x = 0, y = 560 },
            { x = 16, y = 560 },
            { x = 16, y = 160 },
            { x = 208, y = 160 },
            { x = 208, y = 0 }
          },
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "KillPlane",
          shape = "rectangle",
          x = -3712,
          y = 2928,
          width = 4524.69,
          height = 329.181,
          rotation = 0,
          visible = true,
          properties = {
            ["is_visible"] = false,
            ["should_explode"] = false
          }
        },
        {
          id = 392,
          name = "",
          type = "",
          shape = "polygon",
          x = 992,
          y = 2528,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 2144 },
            { x = -192, y = 2144 },
            { x = -192, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
