return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 751,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 288,
          name = "",
          type = "ControlIndicatorTrigger",
          shape = "polygon",
          x = -240,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 496 },
            { x = 720, y = 496 },
            { x = 720, y = 0 }
          },
          properties = {
            ["type"] = "HOLD_DOWN_TO_ACCELERATE"
          }
        },
        {
          id = 290,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -368,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 960, y = 32 },
            { x = 960, y = 720 },
            { x = 0, y = 720 }
          },
          properties = {}
        },
        {
          id = 377,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -496,
          y = -1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -864, y = 0 },
            { x = -864, y = 1088 },
            { x = 0, y = 1088 }
          },
          properties = {}
        },
        {
          id = 402,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = 1136,
          y = -1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 688 },
            { x = 925.877, y = 688 },
            { x = 925.877, y = 0 }
          },
          properties = {}
        },
        {
          id = 423,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -1696,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 992, y = 0 },
            { x = 992, y = 2288 },
            { x = -64, y = 2288 },
            { x = -64, y = 0 }
          },
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 464, y = 0 },
            { x = 464, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {}
        },
        {
          id = 444,
          name = "Hold Down Reminder",
          type = "ControlIndicatorTrigger",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 464, y = 0 },
            { x = 464, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {
            ["type"] = "HOLD_DOWN_TO_ACCELERATE"
          }
        },
        {
          id = 553,
          name = "Bubble Overlap Unpop Preventions",
          type = "CameraFit",
          shape = "polygon",
          x = 3232,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 656 },
            { x = 496, y = 656 },
            { x = 496, y = 0 }
          },
          properties = {}
        },
        {
          id = 600,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = 3503.7,
          y = 304,
          width = 1696.3,
          height = 432,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 627,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = 508.324,
          y = 2105.53,
          width = 2797.59,
          height = 789.077,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = 1302.8,
          y = 2938.19,
          width = 3856,
          height = 592,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 689,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = 1360,
          y = -144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 704, y = 0 },
            { x = 704, y = 672 },
            { x = 16, y = 672 }
          },
          properties = {}
        },
        {
          id = 725,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -448,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 736 },
            { x = 448, y = 736 },
            { x = 448, y = 0 }
          },
          properties = {}
        },
        {
          id = 739,
          name = "Unpause Trigger",
          type = "OverlapTrigger",
          shape = "polygon",
          x = 1008,
          y = 1568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 0 },
            { x = -32, y = -256 },
            { x = 96, y = -256 },
            { x = 96, y = 0 }
          },
          properties = {
            ["signal"] = "unpause",
            ["target"] = { id = 735 }
          }
        },
        {
          id = 741,
          name = "Reset Trigger",
          type = "OverlapTrigger",
          shape = "polygon",
          x = 944,
          y = 1568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -240, y = 0 },
            { x = -240, y = -256 },
            { x = 16, y = -256 },
            { x = 16, y = 0 }
          },
          properties = {
            ["signal"] = "reset",
            ["target"] = { id = 735 }
          }
        },
        {
          id = 747,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = 688,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 336 },
            { x = 2352, y = 336 },
            { x = 2352, y = -272 },
            { x = 304, y = -272 },
            { x = 304, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "back",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 287,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -368,
          y = -1088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 576 },
            { x = 960, y = 576 },
            { x = 960, y = -16 },
            { x = 0, y = -16 }
          },
          properties = {
            ["opacity"] = 0.85,
            ["type"] = "flat"
          }
        },
        {
          id = 357,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1040,
          y = -1408,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = 144 },
            { x = 224, y = 144 },
            { x = 224, y = 928 },
            { x = 0, y = 928 }
          },
          properties = {
            ["opacity"] = 0.5
          }
        },
        {
          id = 358,
          name = "Final",
          type = "Hitbox",
          shape = "polygon",
          x = -886.161,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 182.161, y = -1248 },
            { x = 176, y = 1040 },
            { x = -873.839, y = 1040 },
            { x = -873.839, y = 960 },
            { x = -121.839, y = 960 },
            { x = -121.839, y = -1056 },
            { x = -873.839, y = -1056 },
            { x = -873.839, y = -1248 }
          },
          properties = {}
        },
        {
          id = 368,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -966.161,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -41.839, y = -1056 },
            { x = -41.839, y = 960 },
            { x = -73.839, y = 960 },
            { x = -57.839, y = 944 },
            { x = -57.839, y = -1040 },
            { x = -793.839, y = -1040 },
            { x = -793.839, y = -1056 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = 1248,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 544 },
            { x = 1344, y = 544 },
            { x = 1344, y = 0 }
          },
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "polygon",
          x = -1440,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 151.86 },
            { x = 0, y = 1664 },
            { x = -320, y = 1664 },
            { x = -320, y = 0 }
          },
          properties = {}
        },
        {
          id = 422,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1584,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = -32 },
            { x = 576, y = -32 },
            { x = 576, y = 1984 },
            { x = 144, y = 1984 }
          },
          properties = {
            ["opacity"] = 0.7
          }
        },
        {
          id = 446,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = 80 },
            { x = 320, y = 80 },
            { x = 320, y = 928 },
            { x = 144, y = 928 }
          },
          properties = {}
        },
        {
          id = 593,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = 3648,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -448, y = -16 },
            { x = -448, y = 288 },
            { x = 1552, y = 288 },
            { x = 1552, y = -688 },
            { x = 1792, y = -688 },
            { x = 1792, y = -848 },
            { x = 1296, y = -848 },
            { x = 1296, y = -16 }
          },
          properties = {}
        },
        {
          id = 676,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = 1408,
          y = -64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 224, y = 0 },
            { x = 224, y = -128 },
            { x = 624, y = -128 },
            { x = 624, y = 512 },
            { x = 0, y = 512 }
          },
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -368,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 432 },
            { x = 272, y = 432 },
            { x = 272, y = -80 },
            { x = 416, y = -80 },
            { x = 592, y = -128 },
            { x = 672, y = -128 },
            { x = 736, y = -112 },
            { x = 752, y = -96 },
            { x = 768, y = -32 },
            { x = 768, y = 528 },
            { x = 784, y = 528 },
            { x = 784, y = -32 },
            { x = 816, y = -112 },
            { x = 816, y = -176 },
            { x = 752, y = -176 },
            { x = 672, y = -144 },
            { x = 592, y = -144 },
            { x = 416, y = -192 },
            { x = 192, y = -192 },
            { x = 192, y = 16 },
            { x = 176, y = 32 },
            { x = 80, y = 32 },
            { x = 80, y = 64 },
            { x = 48, y = 80 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 735,
          name = "Path",
          type = "Path",
          shape = "point",
          x = 1045.46,
          y = 1518.66,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["is_paused"] = true,
            ["next"] = { id = 736 },
            ["target"] = { id = 745 }
          }
        },
        {
          id = 736,
          name = "",
          type = "PathNode",
          shape = "point",
          x = 3040,
          y = 1520,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 260,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = 824.95,
          y = 1487.4,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["is_visible"] = false
          }
        },
        {
          id = 261,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 336,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -592, y = 0 },
            { x = -592, y = -208 },
            { x = -704, y = -208 },
            { x = -704, y = 144 },
            { x = 256, y = 144 },
            { x = 256, y = -336 },
            { x = 128, y = -336 },
            { x = 144, y = -320 },
            { x = 144, y = 0 },
            { x = 32, y = 0 },
            { x = 32, y = 32 },
            { x = -160, y = 32 },
            { x = -160, y = 0 },
            { x = -288, y = 0 },
            { x = -288, y = 32 },
            { x = -480, y = 32 },
            { x = -480, y = 0 }
          },
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 176,
          y = -560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -304, y = -16 },
            { x = -144, y = -16 },
            { x = -144, y = 16 },
            { x = -304, y = 16 }
          },
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 352,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -160, y = 0 },
            { x = -160, y = 32 },
            { x = 0, y = 32 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 464,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = -16 },
            { x = -48, y = -32 },
            { x = 0, y = -32 },
            { x = 0, y = -336 },
            { x = 16, y = -320 },
            { x = 16, y = 0 },
            { x = -96, y = 0 },
            { x = -96, y = 32 },
            { x = -112, y = 32 }
          },
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 96,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -64, y = 0 },
            { x = 16, y = -16 },
            { x = 96, y = 0 },
            { x = 96, y = 48 },
            { x = 80, y = 48 },
            { x = 80, y = 16 },
            { x = -48, y = 16 },
            { x = -48, y = 48 },
            { x = -64, y = 48 }
          },
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 544,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = -784, y = 0 },
            { x = -784, y = 112 },
            { x = -800, y = 112 },
            { x = -912, y = 112 },
            { x = -912, y = 96 },
            { x = -800, y = 96 },
            { x = -800, y = -16 },
            { x = 48, y = -16 }
          },
          properties = {}
        },
        {
          id = 276,
          name = "Trampoline Down Introduction",
          type = "Hitbox",
          shape = "polygon",
          x = -368,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = 112, y = 112 },
            { x = 112, y = 0 },
            { x = 960, y = 0 },
            { x = 960, y = -192 },
            { x = 0, y = -192 }
          },
          properties = {}
        },
        {
          id = 286,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -240,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 112, y = -16 },
            { x = 48, y = -32 },
            { x = 0, y = -32 },
            { x = 5.68434e-14, y = -208 },
            { x = -16, y = -208 },
            { x = -16, y = 0 },
            { x = 96, y = 0 },
            { x = 96, y = 32 },
            { x = 112, y = 32 }
          },
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1696,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -48 },
            { x = 0, y = 32 },
            { x = -16, y = 48 },
            { x = -272, y = 48 },
            { x = -272, y = -400 },
            { x = -48, y = -432 },
            { x = -48, y = -528 },
            { x = 336, y = -528 },
            { x = 336, y = -544 },
            { x = -64, y = -544 },
            { x = -64, y = -448 },
            { x = -288, y = -448 },
            { x = -288, y = 64 },
            { x = 0, y = 64 },
            { x = 0, y = 96 },
            { x = -352, y = 96 },
            { x = -352, y = -272 },
            { x = -320, y = -272 },
            { x = -320, y = -496 },
            { x = -320, y = -496 },
            { x = -320, y = -304 },
            { x = -336, y = -304 },
            { x = -368, y = -272 },
            { x = -368, y = 96 },
            { x = -352, y = 112 },
            { x = 0, y = 112 },
            { x = 16, y = 96 },
            { x = 16, y = -48 }
          },
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1728,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = -16, y = 128 },
            { x = -400, y = 128 },
            { x = -416, y = 112 },
            { x = -416, y = -272 },
            { x = -448, y = -304 },
            { x = -464, y = -304 },
            { x = -464, y = -272 },
            { x = -432, y = -272 },
            { x = -432, y = 144 },
            { x = 16, y = 144 },
            { x = 16, y = 64 },
            { x = 304, y = 64 },
            { x = 304, y = -480 },
            { x = 288, y = -480 },
            { x = 288, y = -448 },
            { x = 48, y = -448 },
            { x = 48, y = -432 },
            { x = 288, y = -384 },
            { x = 288, y = 48 },
            { x = 32, y = 48 },
            { x = 16, y = 32 },
            { x = 16, y = -48 },
            { x = 0, y = -48 }
          },
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1296,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 16, y = 368 },
            { x = 32, y = 368 },
            { x = 32, y = 0 },
            { x = 64, y = -32 },
            { x = -16, y = -32 }
          },
          properties = {
            ["axis_y"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["is_visible"] = true,
            ["velocity"] = 2
          }
        },
        {
          id = 308,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1296,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -16 },
            { x = 16, y = -32 },
            { x = 32, y = -32 },
            { x = 48, y = -16 },
            { x = 400, y = -16 },
            { x = 400, y = 0 },
            { x = 32, y = 0 }
          },
          properties = {
            ["axis_x"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["is_visible"] = true,
            ["velocity"] = 2
          }
        },
        {
          id = 309,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1712,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -48 },
            { x = 0, y = 96 },
            { x = -16, y = 112 },
            { x = -16, y = 128 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = -48 }
          },
          properties = {
            ["axis_y"] = -1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["is_visible"] = true,
            ["velocity"] = 0.6
          }
        },
        {
          id = 311,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1680,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = -272, y = 0 },
            { x = -272, y = -512 },
            { x = -48, y = -512 },
            { x = -48, y = -608 },
            { x = 368, y = -608 },
            { x = 368, y = -704 },
            { x = -304, y = -704 },
            { x = -304, y = -336 },
            { x = -336, y = -336 },
            { x = -336, y = 32 },
            { x = 16, y = 32 }
          },
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1296,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -64, y = 0 },
            { x = -64, y = 480 },
            { x = 64.2859, y = 480 },
            { x = 928, y = 480 },
            { x = 928, y = -208 },
            { x = 736, y = -208 },
            { x = 736, y = 336 },
            { x = 448, y = 336 },
            { x = 448, y = 416 },
            { x = 0, y = 416 }
          },
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 1744,
          y = 352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = 16, y = 80 },
            { x = 80, y = 80 }
          },
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 1696,
          y = 352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = -16, y = 80 },
            { x = -80, y = 80 }
          },
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 736,
          y = 1616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = -320 },
            { x = 64, y = -320 },
            { x = 64, y = -448 },
            { x = -144, y = -448 },
            { x = -144, y = -96 },
            { x = -160, y = -112 },
            { x = -160, y = -448 },
            { x = -144, y = -464 },
            { x = 64, y = -464 },
            { x = 80, y = -448 },
            { x = 80, y = -304 },
            { x = 64, y = -304 },
            { x = -32, y = -304 },
            { x = -32, y = -16 },
            { x = -16, y = 0 },
            { x = 2304, y = 0 },
            { x = 2304, y = 16 },
            { x = -48, y = 16 }
          },
          properties = {
            ["unjumpable"] = true,
            ["unwalkable"] = true
          }
        },
        {
          id = 324,
          name = "",
          type = "KillPlane",
          shape = "polygon",
          x = 736,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -16 },
            { x = -32, y = 32 },
            { x = 2304, y = 32 },
            { x = 2304, y = -16 }
          },
          properties = {
            ["hue"] = "player",
            ["velocity"] = 1.5
          }
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "polygon",
          x = 800,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -48 },
            { x = -176, y = -48 },
            { x = -176, y = 384 },
            { x = 2240, y = 384 },
            { x = 2240, y = 336 },
            { x = -112, y = 336 },
            { x = -112, y = 0 }
          },
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 832,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -160 },
            { x = -16, y = -176 },
            { x = -257.187, y = -176 },
            { x = -272, y = -160 },
            { x = -272, y = 192 },
            { x = -288, y = 208 },
            { x = -288, y = -192 },
            { x = 16, y = -192 },
            { x = 16, y = -16 },
            { x = 160, y = -16 },
            { x = 160, y = -96 },
            { x = 176, y = -96 },
            { x = 176, y = 0 }
          },
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -273.341,
          y = -318.659,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -277.455, y = 0 },
            { x = -277.455, y = -17.341 },
            { x = 0, y = -17.341 }
          },
          properties = {
            ["axis_x"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player"
          }
        },
        {
          id = 338,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1232,
          y = -480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = -784 },
            { x = 608, y = -784 },
            { x = 608, y = -736 },
            { x = 480, y = -736 },
            { x = 480, y = 224 },
            { x = 0, y = 224 }
          },
          properties = {}
        },
        {
          id = 339,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -816,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 192, y = -256 },
            { x = 192, y = -240 },
            { x = 0, y = -240 },
            { x = 0, y = 544 },
            { x = -16, y = 544 },
            { x = -16, y = -256 }
          },
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 343,
          name = "Bounce Ladder",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1025,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 401, y = -384 },
            { x = 401, y = -368 },
            { x = 113, y = -368 },
            { x = 1, y = -272 },
            { x = 0, y = 480 },
            { x = -207, y = 480 },
            { x = -207, y = 464 },
            { x = -14.9641, y = 464 },
            { x = -15, y = -384 }
          },
          properties = {}
        },
        {
          id = 344,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 355,
          name = "",
          type = "",
          shape = "polygon",
          x = -1040,
          y = -544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -192, y = -16 },
            { x = -192, y = -64 },
            { x = -64, y = -64 },
            { x = -64, y = -928 },
            { x = 416, y = -928 },
            { x = 416, y = -864 },
            { x = 0, y = -864 }
          },
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1136,
          y = 2096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -32, y = -32 },
            { x = -32, y = -80 },
            { x = 0, y = -96 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1136,
          y = 1856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 320 },
            { x = 16, y = 320 },
            { x = 16, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1120,
          y = 1840,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 64 },
            { x = 0, y = 336 },
            { x = 16, y = 336 },
            { x = 16, y = 64 },
            { x = 64, y = 64 },
            { x = 64, y = 48 },
            { x = -16, y = 48 },
            { x = -16, y = 64 }
          },
          properties = {}
        },
        {
          id = 364,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1328,
          y = 1680,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 0 },
            { x = -16, y = -112 },
            { x = 0, y = -112 }
          },
          properties = {}
        },
        {
          id = 366,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1312,
          y = 1776,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1328,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 0, y = -48 },
            { x = 16, y = -48 },
            { x = 16, y = -64 },
            { x = -64, y = -64 },
            { x = -64, y = -48 },
            { x = -32, y = -48 },
            { x = -32, y = 240 },
            { x = 0, y = 240 },
            { x = 0, y = 96 },
            { x = -16, y = 96 },
            { x = -16, y = -16 }
          },
          properties = {}
        },
        {
          id = 382,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1840,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -592, y = -16 },
            { x = -592, y = -208 },
            { x = -704, y = -208 },
            { x = -704, y = 288 },
            { x = 752, y = 288 },
            { x = 752, y = -336 },
            { x = 624, y = -336 },
            { x = 640, y = -320 },
            { x = 640, y = -16 },
            { x = -96, y = -16 },
            { x = -128, y = -32 },
            { x = -256, y = -32 },
            { x = -288, y = -16 }
          },
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1968,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 496, y = -32 },
            { x = 496, y = -336 },
            { x = 512, y = -320 },
            { x = 512, y = -16 },
            { x = 480, y = -16 }
          },
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2048,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -96 },
            { x = 0, y = 96 },
            { x = 144, y = 96 },
            { x = 144, y = -96 },
            { x = 544, y = -96 },
            { x = 544, y = -80 },
            { x = 160, y = -80 },
            { x = 160, y = 96 },
            { x = 160, y = 112 },
            { x = -16, y = 112 },
            { x = -16, y = -80 },
            { x = -784, y = -80 },
            { x = -784, y = 112 },
            { x = -800, y = 112 },
            { x = -912, y = 112 },
            { x = -912, y = 96 },
            { x = -800, y = 96 },
            { x = -800, y = -96 }
          },
          properties = {}
        },
        {
          id = 388,
          name = "Bubble Intro",
          type = "Hitbox",
          shape = "polygon",
          x = 1136,
          y = -1072,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = 112, y = 112 },
            { x = 112, y = -80 },
            { x = 912, y = -80 },
            { x = 912, y = 112 },
            { x = 1056, y = 112 },
            { x = 1056, y = -80 },
            { x = 1456, y = -80 },
            { x = 1456, y = -272 },
            { x = 0, y = -272 }
          },
          properties = {}
        },
        {
          id = 389,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1264,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = -224 },
            { x = -128, y = -224 },
            { x = -128, y = -208 },
            { x = -16, y = -208 },
            { x = -16, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 1264,
          y = -944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 391 }
          }
        },
        {
          id = 391,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 1264,
          y = -816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1600,
          y = -752,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 2272,
          y = -736,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 2352,
          y = -864,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1744,
          y = -880,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1536,
          y = -944,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "Coin",
          shape = "point",
          x = 1648,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1232,
          y = 1475,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 112, y = 32 },
            { x = 112, y = 0 }
          },
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1136,
          y = 1555,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 0, y = -48 },
            { x = 16, y = -48 },
            { x = 16, y = -80 },
            { x = 0, y = -80 },
            { x = 0, y = -400 },
            { x = 16, y = -400 },
            { x = 16, y = -512 },
            { x = 0, y = -512 },
            { x = 0, y = -544 },
            { x = -32, y = -544 },
            { x = -32, y = -560 },
            { x = 80, y = -560 },
            { x = 80, y = -544 },
            { x = 32, y = -544 },
            { x = 32, y = -16 }
          },
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1136,
          y = 1075,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = 80 },
            { x = 16, y = 80 },
            { x = 16, y = -32 }
          },
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1312,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -208 },
            { x = 0, y = -208 },
            { x = 0, y = -512 },
            { x = 32, y = -512 },
            { x = 32, y = -528 },
            { x = -448, y = -528 },
            { x = -448, y = -512 },
            { x = -128, y = -512 },
            { x = -128, y = 1152 },
            { x = -368, y = 1152 },
            { x = -368, y = 1168 },
            { x = -112, y = 1168 },
            { x = -110.68, y = -512 },
            { x = -32, y = -512 },
            { x = -32, y = -496 },
            { x = -16, y = -496 }
          },
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1152,
          y = 768,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1264,
          y = 624,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1328,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -384 },
            { x = -16, y = 48 },
            { x = 16, y = 48 },
            { x = 16, y = -96 },
            { x = 0, y = -96 },
            { x = 0, y = -384 }
          },
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "",
          shape = "polygon",
          x = -1312,
          y = 944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 0 },
            { x = -32, y = 16 },
            { x = 0, y = 16 }
          },
          properties = {}
        },
        {
          id = 418,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -1384.05,
          y = 536.563,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1152,
          y = 496,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "",
          shape = "polygon",
          x = -224,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 144, y = 80 },
            { x = 144, y = 480 },
            { x = 320, y = 480 },
            { x = 320, y = -192 },
            { x = 464, y = -192 },
            { x = 464, y = 704 },
            { x = 0, y = 704 }
          },
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -64,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -128 },
            { x = 144, y = -128 },
            { x = 144, y = -96 },
            { x = 0, y = -96 }
          },
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -80,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -144, y = 64 },
            { x = 16, y = 64 },
            { x = 16, y = 464 },
            { x = 160, y = 464 },
            { x = 160, y = -208 },
            { x = 320, y = -208 },
            { x = 320, y = -192 },
            { x = 176, y = -192 },
            { x = 176, y = 480 },
            { x = 0, y = 480 },
            { x = 0, y = 80 },
            { x = -144, y = 80 }
          },
          properties = {}
        },
        {
          id = 430,
          name = "",
          type = "",
          shape = "polygon",
          x = -64,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = -160, y = 0 },
            { x = -160, y = -416 },
            { x = 304, y = -416 },
            { x = 304, y = -272 },
            { x = -16, y = -272 }
          },
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -80,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -144, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = -256 },
            { x = 320, y = -256 },
            { x = 320, y = -272 },
            { x = 0, y = -272 },
            { x = 0, y = 0 },
            { x = -144, y = 0 }
          },
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = 2016,
          y = -1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 688 },
            { x = 576, y = 688 },
            { x = 576, y = 0 }
          },
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 3216,
          y = -496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 240, y = 16 },
            { x = 240, y = 32 },
            { x = 400, y = 32 },
            { x = 400, y = -368 },
            { x = 512, y = -368 },
            { x = 512, y = 144 },
            { x = 0, y = 144 }
          },
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 3600,
          y = -880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 0 },
            { x = 128, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 416 },
            { x = -144, y = 416 },
            { x = -144, y = 400 },
            { x = -384, y = 400 },
            { x = -384, y = 384 },
            { x = -128, y = 384 },
            { x = -128, y = 400 },
            { x = -32, y = 400 },
            { x = -32, y = 384 },
            { x = -16, y = 384 },
            { x = 0, y = 368 },
            { x = 0, y = 0 },
            { x = 16.6075, y = 0 }
          },
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 3472,
          y = -512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 96, y = 32 },
            { x = 96, y = 0 }
          },
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 3248,
          y = -624,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 547 }
          }
        },
        {
          id = 547,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 3248,
          y = -496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 3216,
          y = -640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 208, y = 0 },
            { x = 208, y = -352 },
            { x = 512, y = -352 },
            { x = 512, y = -416 },
            { x = 0, y = -416 }
          },
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 3440,
          y = -880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -112 },
            { x = -16, y = 240 },
            { x = -224, y = 240 },
            { x = -224, y = 256 },
            { x = 0, y = 256 },
            { x = 0, y = -95.3885 },
            { x = 288, y = -96 },
            { x = 288, y = -112 }
          },
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 3474.28,
          y = -761.209,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 3200,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 432, y = -16 },
            { x = 432, y = -480 },
            { x = 0, y = -480 }
          },
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 3296,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = 0, y = 16 },
            { x = 128, y = 16 },
            { x = 144, y = 0 },
            { x = 352, y = 0 },
            { x = 352, y = -80 },
            { x = 1664, y = -80 },
            { x = 1664, y = -208 },
            { x = 1648, y = -208 },
            { x = 1648, y = -96 },
            { x = 336, y = -96 },
            { x = 334.607, y = -16 },
            { x = -96, y = -16 },
            { x = -96, y = 0 }
          },
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 3200,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 448, y = 16 },
            { x = 448, y = 0 },
            { x = 720.136, y = 0 },
            { x = 720, y = 16 },
            { x = 912, y = 16 },
            { x = 912, y = 0 },
            { x = 1312, y = 0 },
            { x = 1312, y = 16 },
            { x = 1504, y = 16 },
            { x = 1504, y = 0 },
            { x = 2000, y = 0 },
            { x = 2000, y = -240 },
            { x = 1984, y = -240 },
            { x = 1984, y = -448 },
            { x = 2000, y = -448 },
            { x = 2000, y = -624 },
            { x = 2000, y = -960 },
            { x = 2240, y = -960 },
            { x = 2240, y = 0 },
            { x = 2240, y = 208 },
            { x = 0, y = 208 }
          },
          properties = {}
        },
        {
          id = 559,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 3296,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = 0, y = -16 },
            { x = 128, y = -16 },
            { x = 144, y = 0 },
            { x = 352, y = 0 },
            { x = 352, y = 16 },
            { x = -96, y = 16 },
            { x = -96, y = 0 }
          },
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "KillPlane",
          shape = "ellipse",
          x = 3920,
          y = 576,
          width = 192,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 565,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 3920,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 0 },
            { x = -32, y = 16 },
            { x = 0, y = 16 },
            { x = 0, y = 32 },
            { x = 192, y = 32 },
            { x = 192, y = 16 },
            { x = 224, y = 16 },
            { x = 208, y = 0 },
            { x = 192, y = 0 }
          },
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "KillPlane",
          shape = "ellipse",
          x = 4512,
          y = 576,
          width = 192,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 567,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 4512,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 0 },
            { x = -32, y = 16 },
            { x = 0, y = 16 },
            { x = 0, y = 32 },
            { x = 192, y = 32 },
            { x = 192, y = 16 },
            { x = 224, y = 16 },
            { x = 208, y = 0 },
            { x = 192, y = 0 }
          },
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "KillPlane",
          shape = "ellipse",
          x = 4512,
          y = 304,
          width = 192,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 570,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 5168,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 32, y = -240 },
            { x = 16, y = -240 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 572,
          name = "",
          type = "BouncePad",
          shape = "ellipse",
          x = 5008,
          y = 608,
          width = 112,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 574,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 4992,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 0 },
            { x = -32, y = 16 },
            { x = 0, y = 16 },
            { x = 0, y = 32 },
            { x = 144, y = 32 },
            { x = 144, y = 16 },
            { x = 176, y = 16 },
            { x = 160, y = 0 },
            { x = 144, y = 0 }
          },
          properties = {}
        },
        {
          id = 578,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 5200,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -48 },
            { x = -16, y = -48 },
            { x = -16, y = -64 },
            { x = -32, y = -80 },
            { x = -32, y = -192 },
            { x = -16, y = -208 },
            { x = -16, y = -332.346 },
            { x = -32, y = -352 },
            { x = -32, y = -464 },
            { x = -16, y = -480 },
            { x = -16, y = -576 },
            { x = 240, y = -576 },
            { x = 240, y = -560 },
            { x = 0, y = -560 }
          },
          properties = {}
        },
        {
          id = 579,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 4928,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = -64 },
            { x = 16, y = -64 },
            { x = 16, y = -208 },
            { x = 32, y = -208 }
          },
          properties = {}
        },
        {
          id = 581,
          name = "",
          type = "BouncePad",
          shape = "ellipse",
          x = 5104,
          y = 80,
          width = 112,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 585,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 4944,
          y = 144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 16, y = -16 },
            { x = 16, y = -96 },
            { x = 32, y = -112 },
            { x = 32, y = -224 },
            { x = 16, y = -240 },
            { x = 16, y = -576 },
            { x = 496, y = -576 },
            { x = 496, y = -592 },
            { x = 0, y = -592 }
          },
          properties = {
            ["unwalkable"] = false
          }
        },
        {
          id = 590,
          name = "",
          type = "BouncePad",
          shape = "ellipse",
          x = 4928,
          y = -80,
          width = 112,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 591,
          name = "",
          type = "BouncePad",
          shape = "ellipse",
          x = 5104,
          y = -192,
          width = 112,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {
            ["render_priority"] = -1
          }
        },
        {
          id = 592,
          name = "",
          type = "Fireflies",
          shape = "point",
          x = 4976,
          y = 208,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = 3
          }
        },
        {
          id = 594,
          name = "",
          type = "Fireflies",
          shape = "point",
          x = 5168,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = 4
          }
        },
        {
          id = 599,
          name = "Checkpoint",
          type = "Checkpoint",
          shape = "point",
          x = 3360,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 655,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 1424,
          y = 352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 80 },
            { x = 80, y = 80 }
          },
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 2016,
          y = 352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 80 },
            { x = -80, y = 80 }
          },
          properties = {}
        },
        {
          id = 667,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 1696,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = -48 },
            { x = -32, y = -48 }
          },
          properties = {}
        },
        {
          id = 668,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 1696,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 669 }
          }
        },
        {
          id = 669,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 1744,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 670,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 1648,
          y = -64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 671 }
          }
        },
        {
          id = 671,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 1776,
          y = -64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 674,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 1376,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 675 }
          }
        },
        {
          id = 675,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 1264,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 685,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -352,
          y = 848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = 48, y = 64 },
            { x = -16, y = 64 }
          },
          properties = {}
        },
        {
          id = 692,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -288,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 768, y = -288 },
            { x = 80, y = -288 },
            { x = 80, y = -64 },
            { x = -32, y = -64 },
            { x = -32, y = 16 },
            { x = 0, y = 0 },
            { x = 0, y = -32 },
            { x = 96.7517, y = -32 },
            { x = 112, y = -48 },
            { x = 112, y = -256 },
            { x = 336, y = -256 },
            { x = 512, y = -208 },
            { x = 592, y = -208 },
            { x = 672, y = -240 },
            { x = 736, y = -240 },
            { x = 736, y = -176 },
            { x = 704, y = -96 },
            { x = 704, y = 464 },
            { x = 736, y = 464 },
            { x = 736, y = -96 },
            { x = 768, y = -96 }
          },
          properties = {}
        },
        {
          id = 697,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -112,
          y = 848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = -64, y = 64 },
            { x = 16, y = 64 }
          },
          properties = {}
        },
        {
          id = 699,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -144,
          y = 350,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 18 },
            { x = 48, y = -62 },
            { x = -32, y = -62 }
          },
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -400,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -64 },
            { x = 32, y = -64 },
            { x = 32, y = 368 },
            { x = 144, y = 368 },
            { x = 160, y = 384 },
            { x = 160, y = 400.32 },
            { x = 144, y = 416 },
            { x = 16, y = 416 },
            { x = 0, y = 400 }
          },
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -224,
          y = 944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = -16, y = 32 },
            { x = -176, y = 32 },
            { x = -192, y = 16 },
            { x = -192, y = -464 },
            { x = -224, y = -464 },
            { x = -224, y = 64 },
            { x = 160, y = 64 },
            { x = 160, y = -512 },
            { x = 592, y = -512 },
            { x = 592, y = 64 },
            { x = 624, y = 64 },
            { x = 624, y = -496 },
            { x = 608, y = -560 },
            { x = 592, y = -576 },
            { x = 528, y = -592 },
            { x = 448, y = -592 },
            { x = 272, y = -544 },
            { x = 128, y = -544 },
            { x = 128, y = -32 },
            { x = 16, y = -32 },
            { x = 0, y = -16 }
          },
          properties = {}
        },
        {
          id = 718,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 48,
          y = 288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -80, y = 0 },
            { x = -80, y = 112 },
            { x = 0, y = 112 },
            { x = 176, y = 64 },
            { x = 176, y = 64 },
            { x = 176, y = 48 },
            { x = 176, y = 48 },
            { x = 0, y = 0 }
          },
          properties = {
            ["axis_x"] = 1,
            ["hue"] = "player",
            ["velocity"] = 1
          }
        },
        {
          id = 721,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 688,
          y = 368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -240, y = 0 },
            { x = -304, y = -64 },
            { x = -240, y = -64 }
          },
          properties = {}
        },
        {
          id = 722,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 448,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = -48, y = 560 },
            { x = -32, y = 560 },
            { x = -32, y = 0 }
          },
          properties = {
            ["axis_y"] = 1,
            ["hue"] = "player"
          }
        },
        {
          id = 723,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 224,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 0 }
          },
          properties = {
            ["axis_x"] = 1,
            ["hue"] = "player",
            ["velocity"] = 2
          }
        },
        {
          id = 743,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 976,
          y = 1312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "KILL_PLANE",
            ["other"] = { id = 744 }
          }
        },
        {
          id = 744,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 976,
          y = 1568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 745,
          name = "Target",
          type = "BouncePad",
          shape = "ellipse",
          x = 1008,
          y = 1488,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 746,
          name = "Fireflies",
          type = "Fireflies",
          shape = "point",
          x = 1040,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 748,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 3040,
          y = 1568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "KILL_PLANE",
            ["other"] = { id = 749 }
          }
        },
        {
          id = 749,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 704,
          y = 1568,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 750,
          name = "",
          type = "",
          shape = "polygon",
          x = 736,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 176, y = 0 },
            { x = 176, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 271,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -240,
          y = -928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 272 }
          }
        },
        {
          id = 272,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -240,
          y = -784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "Flies",
          type = "Fireflies",
          shape = "point",
          x = 112,
          y = -704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = "3"
          }
        },
        {
          id = 428,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -64,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 429 }
          }
        },
        {
          id = 429,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -64,
          y = 1648,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "Checkpoint",
          shape = "point",
          x = -154.909,
          y = 1597.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["is_invisible"] = false
          }
        },
        {
          id = 447,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 96,
          y = 1232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 448 }
          }
        },
        {
          id = 448,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 96,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 595,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 4738.11,
          y = -568.178,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -432,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 704 }
          }
        },
        {
          id = 704,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -384,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 705,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -416,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -64 },
            { x = 0, y = 416 },
            { x = 16, y = 400 },
            { x = 16, y = -64 }
          },
          properties = {
            ["axis_y"] = -1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["velocity"] = "0.75"
          }
        },
        {
          id = 706,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -256,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = -128, y = 16 },
            { x = -128, y = 0 }
          },
          properties = {
            ["axis_x"] = -1,
            ["has_outline"] = false,
            ["hue"] = "player"
          }
        },
        {
          id = 707,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -384,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = -16 },
            { x = -32, y = 0 },
            { x = -16, y = 16 },
            { x = 0, y = 16 }
          },
          properties = {
            ["aixs_y"] = -1,
            ["axis_x"] = -1,
            ["has_outline"] = false,
            ["hue"] = "player"
          }
        },
        {
          id = 708,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -240,
          y = 944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 32 },
            { x = 0, y = 32 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {
            ["axis_x"] = -1,
            ["axis_y"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player"
          }
        },
        {
          id = 709,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -256,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = 16 }
          },
          properties = {
            ["axis_y"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player"
          }
        },
        {
          id = 710,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -208,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 711 }
          }
        },
        {
          id = 711,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -256,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 712,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -368,
          y = 560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -64 },
            { x = 0, y = 0 },
            { x = 24.2074, y = 16 },
            { x = 48, y = 0 },
            { x = 48, y = -64 }
          },
          properties = {
            ["axis_y"] = 1,
            ["hue"] = "player",
            ["velocity"] = 0.75
          }
        },
        {
          id = 713,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -320,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 714 }
          }
        },
        {
          id = 714,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -368,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
