return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 530,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 288,
          name = "",
          type = "ControlIndicatorTrigger",
          shape = "polygon",
          x = -240,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 496 },
            { x = 720, y = 496 },
            { x = 720, y = 0 }
          },
          properties = {
            ["type"] = "HOLD_DOWN_TO_ACCELERATE"
          }
        },
        {
          id = 290,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -368,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 960, y = 32 },
            { x = 960, y = 720 },
            { x = 0, y = 720 }
          },
          properties = {}
        },
        {
          id = 377,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -496,
          y = -1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -864, y = 0 },
            { x = -864, y = 1088 },
            { x = 0, y = 1088 }
          },
          properties = {}
        },
        {
          id = 402,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = 1136,
          y = -1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 688 },
            { x = 1024, y = 688 },
            { x = 1024, y = 0 }
          },
          properties = {}
        },
        {
          id = 404,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = 1136,
          y = -1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 688 },
            { x = 1824, y = 688 },
            { x = 1824, y = 0 }
          },
          properties = {}
        },
        {
          id = 423,
          name = "",
          type = "CameraBounds",
          shape = "polygon",
          x = -1696,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 992, y = 0 },
            { x = 992, y = 2288 },
            { x = -64, y = 2288 },
            { x = -64, y = 0 }
          },
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 464, y = 0 },
            { x = 464, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {}
        },
        {
          id = 444,
          name = "Hold Down Reminder",
          type = "ControlIndicatorTrigger",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 464, y = 0 },
            { x = 464, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {
            ["type"] = "HOLD_DOWN_TO_ACCELERATE"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "back",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 287,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -368,
          y = -1088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 576 },
            { x = 960, y = 576 },
            { x = 960, y = -16 },
            { x = 0, y = -16 }
          },
          properties = {
            ["opacity"] = 0.85,
            ["type"] = "flat"
          }
        },
        {
          id = 326,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -368,
          y = -144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 320 },
            { x = 1184, y = 320 },
            { x = 1184, y = -48 },
            { x = -112, y = -48 }
          },
          properties = {}
        },
        {
          id = 357,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1040,
          y = -1408,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = 144 },
            { x = 224, y = 144 },
            { x = 224, y = 928 },
            { x = 0, y = 928 }
          },
          properties = {
            ["opacity"] = 0.5
          }
        },
        {
          id = 358,
          name = "Final",
          type = "Hitbox",
          shape = "polygon",
          x = -886.161,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 182.161, y = -1248 },
            { x = 176, y = 1040 },
            { x = -873.839, y = 1040 },
            { x = -873.839, y = 960 },
            { x = -121.839, y = 960 },
            { x = -121.839, y = -1056 },
            { x = -873.839, y = -1056 },
            { x = -873.839, y = -1248 }
          },
          properties = {}
        },
        {
          id = 368,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -966.161,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -41.839, y = -1056 },
            { x = -41.839, y = 960 },
            { x = -73.839, y = 960 },
            { x = -57.839, y = 944 },
            { x = -57.839, y = -1040 },
            { x = -793.839, y = -1040 },
            { x = -793.839, y = -1056 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = 1248,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 544 },
            { x = 1344, y = 544 },
            { x = 1344, y = 0 }
          },
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "BubbleField",
          shape = "polygon",
          x = 1008,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = 112 },
            { x = 32, y = 240 },
            { x = 416, y = 256 },
            { x = 672, y = 208 },
            { x = 720, y = 144 },
            { x = 704, y = 0 },
            { x = 576, y = -128 },
            { x = 368, y = -176 },
            { x = 240, y = -176 },
            { x = 64, y = -64 }
          },
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "polygon",
          x = -1440,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 151.86 },
            { x = 0, y = 1664 },
            { x = -320, y = 1664 },
            { x = -320, y = 0 }
          },
          properties = {}
        },
        {
          id = 422,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1584,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = -32 },
            { x = 576, y = -32 },
            { x = 576, y = 1984 },
            { x = 144, y = 1984 }
          },
          properties = {
            ["opacity"] = 0.7
          }
        },
        {
          id = 446,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -224,
          y = 1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = 80 },
            { x = 320, y = 80 },
            { x = 320, y = 928 },
            { x = 144, y = 928 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 260,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = 919.014,
          y = 1783.22,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 336,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -592, y = 0 },
            { x = -592, y = -208 },
            { x = -704, y = -208 },
            { x = -704, y = 144 },
            { x = 256, y = 144 },
            { x = 256, y = -336 },
            { x = 128, y = -336 },
            { x = 144, y = -320 },
            { x = 144, y = 0 },
            { x = 32, y = 0 },
            { x = 32, y = 32 },
            { x = -160, y = 32 },
            { x = -160, y = 0 },
            { x = -288, y = 0 },
            { x = -288, y = 32 },
            { x = -480, y = 32 },
            { x = -480, y = 0 }
          },
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 176,
          y = -560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -304, y = -16 },
            { x = -144, y = -16 },
            { x = -144, y = 16 },
            { x = -304, y = 16 }
          },
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 352,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -160, y = 0 },
            { x = -160, y = 32 },
            { x = 0, y = 32 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 464,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = -16 },
            { x = -48, y = -32 },
            { x = 0, y = -32 },
            { x = 0, y = -336 },
            { x = 16, y = -320 },
            { x = 16, y = 0 },
            { x = -96, y = 0 },
            { x = -96, y = 32 },
            { x = -112, y = 32 }
          },
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 96,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -64, y = 0 },
            { x = 16, y = -16 },
            { x = 96, y = 0 },
            { x = 96, y = 48 },
            { x = 80, y = 48 },
            { x = 80, y = 16 },
            { x = -48, y = 16 },
            { x = -48, y = 48 },
            { x = -64, y = 48 }
          },
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 544,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = -784, y = 0 },
            { x = -784, y = 112 },
            { x = -800, y = 112 },
            { x = -912, y = 112 },
            { x = -912, y = 96 },
            { x = -800, y = 96 },
            { x = -800, y = -16 },
            { x = 48, y = -16 }
          },
          properties = {}
        },
        {
          id = 276,
          name = "Trampoline Down Introduction",
          type = "Hitbox",
          shape = "polygon",
          x = -368,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = 112, y = 112 },
            { x = 112, y = 0 },
            { x = 960, y = 0 },
            { x = 960, y = -192 },
            { x = 0, y = -192 }
          },
          properties = {}
        },
        {
          id = 286,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -240,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 112, y = -16 },
            { x = 48, y = -32 },
            { x = 0, y = -32 },
            { x = 5.68434e-14, y = -208 },
            { x = -16, y = -208 },
            { x = -16, y = 0 },
            { x = 96, y = 0 },
            { x = 96, y = 32 },
            { x = 112, y = 32 }
          },
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 16,
          y = 784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = 32 },
            { x = -16, y = 48 },
            { x = -256, y = 48 },
            { x = -256, y = -496 },
            { x = -272, y = -496 },
            { x = -272, y = 64 },
            { x = 0, y = 64 },
            { x = 0, y = 112 },
            { x = -336, y = 112 },
            { x = -336, y = -272 },
            { x = -304, y = -272 },
            { x = -304, y = -496 },
            { x = -320, y = -496 },
            { x = -320, y = -304 },
            { x = -352, y = -272 },
            { x = -352, y = 112 },
            { x = -336, y = 128 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = -32 }
          },
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 64,
          y = 784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 128 },
            { x = -32, y = 144 },
            { x = -400, y = 144 },
            { x = -416, y = 128 },
            { x = -416, y = -272 },
            { x = -448, y = -304 },
            { x = -464, y = -304 },
            { x = -464, y = -272 },
            { x = -432, y = -272 },
            { x = -432, y = 160 },
            { x = 0, y = 160 },
            { x = 0, y = 64 },
            { x = 272, y = 64 },
            { x = 272, y = -480 },
            { x = 256, y = -480 },
            { x = 256, y = 48 },
            { x = 16, y = 48 },
            { x = 0, y = 32 },
            { x = 0, y = -32 },
            { x = -16, y = -32 }
          },
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -368,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 16, y = 384 },
            { x = 32, y = 384 },
            { x = 32, y = 0 },
            { x = 64, y = -32 },
            { x = -16, y = -32 }
          },
          properties = {
            ["axis_y"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["velocity"] = 1
          }
        },
        {
          id = 308,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -368,
          y = 912,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = 32, y = -16 },
            { x = 48, y = 0 },
            { x = 384, y = 0 },
            { x = 384, y = 16 },
            { x = 32, y = 16 }
          },
          properties = {
            ["axis_x"] = 1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["velocity"] = 1
          }
        },
        {
          id = 309,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 32,
          y = 784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = 112 },
            { x = -16, y = 128 },
            { x = -16, y = 144 },
            { x = 0, y = 144 },
            { x = 16, y = 128 },
            { x = 16, y = -32 }
          },
          properties = {
            ["axis_y"] = -1,
            ["has_outline"] = false,
            ["hue"] = "player",
            ["velocity"] = 1
          }
        },
        {
          id = 311,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 16,
          y = 848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -272, y = 0 },
            { x = -272, y = -560 },
            { x = -304, y = -560 },
            { x = -304, y = -336 },
            { x = -336, y = -336 },
            { x = -336, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -410.9,
          y = 445.505,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -64, y = 0 },
            { x = -64, y = 480 },
            { x = 880, y = 480 },
            { x = 880, y = -208 },
            { x = 704, y = -208 },
            { x = 704, y = 336 },
            { x = 432, y = 336 },
            { x = 432, y = 432 },
            { x = 0, y = 432 }
          },
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 64,
          y = 752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = 16, y = 80 },
            { x = 80, y = 80 }
          },
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 16,
          y = 752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = -16, y = 80 },
            { x = -80, y = 80 }
          },
          properties = {}
        },
        {
          id = 318,
          name = "",
          type = "",
          shape = "polygon",
          x = -96,
          y = 32,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -208, y = 32 },
            { x = 128, y = 32 },
            { x = 128, y = 0 },
            { x = -208, y = 0 }
          },
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -352,
          y = 144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = -320 },
            { x = 64, y = -320 },
            { x = 64, y = -448 },
            { x = -144, y = -448 },
            { x = -144, y = -96 },
            { x = -160, y = -112 },
            { x = -160, y = -448 },
            { x = -144, y = -464 },
            { x = 64, y = -464 },
            { x = 80, y = -448 },
            { x = 80, y = -304 },
            { x = 64, y = -304 },
            { x = -32, y = -304 },
            { x = -32, y = -16 },
            { x = -16, y = 0 },
            { x = 1168, y = 0 },
            { x = 1168, y = 16 },
            { x = -48, y = 16 }
          },
          properties = {
            ["unjumpable"] = true,
            ["unwalkable"] = true
          }
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "polygon",
          x = 256,
          y = 32,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 321,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 816,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 323 }
          }
        },
        {
          id = 323,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -336,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 324,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -352,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -16 },
            { x = 16, y = 32 },
            { x = 1168, y = 32 },
            { x = 1168, y = -16 }
          },
          properties = {
            ["axis_x"] = -1,
            ["hue"] = "player",
            ["velocity"] = 1.5
          }
        },
        {
          id = 327,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -352,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -48 },
            { x = -32, y = -48 },
            { x = -32, y = 32 },
            { x = 16, y = 32 }
          },
          properties = {
            ["axis_y"] = -1,
            ["hue"] = "player",
            ["velocity"] = 0.75
          }
        },
        {
          id = 328,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -336,
          y = -160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player",
            ["other"] = { id = 329 }
          }
        },
        {
          id = 329,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -336,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["hue"] = "player"
          }
        },
        {
          id = 330,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -352,
          y = -80,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -80 },
            { x = -32, y = -80 },
            { x = -32, y = 144 },
            { x = 16, y = 144 }
          },
          properties = {
            ["axis_x"] = 1,
            ["axis_y"] = 0,
            ["hue"] = "player",
            ["velocity"] = 0.5
          }
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "polygon",
          x = -288,
          y = -176,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -48 },
            { x = -176, y = -48 },
            { x = -176, y = 384 },
            { x = 1104, y = 384 },
            { x = 1104, y = 336 },
            { x = -112, y = 336 },
            { x = -112, y = 0 }
          },
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -256,
          y = -160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -160 },
            { x = -16, y = -176 },
            { x = -257.187, y = -176 },
            { x = -272, y = -160 },
            { x = -272, y = 192 },
            { x = -288, y = 208 },
            { x = -288, y = -192 },
            { x = 16, y = -192 },
            { x = 16, y = -16 },
            { x = 992, y = -16 },
            { x = 992, y = 0 }
          },
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -288,
          y = -304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -32 },
            { x = 16, y = -16 },
            { x = 0, y = -16 },
            { x = 16, y = 0 },
            { x = 16, y = 144 },
            { x = 32, y = 144 },
            { x = 32, y = -32 }
          },
          properties = {
            ["axis_y"] = 1
          }
        },
        {
          id = 334,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -272,
          y = -320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -256, y = 0 },
            { x = -256, y = -16 },
            { x = 0, y = -16 }
          },
          properties = {
            ["axis_x"] = 1
          }
        },
        {
          id = 335,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -512,
          y = -320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 0, y = 16 },
            { x = 0, y = 384 },
            { x = -16, y = 384 },
            { x = -16, y = 0 }
          },
          properties = {
            ["axis_y"] = -1
          }
        },
        {
          id = 336,
          name = "",
          type = "",
          shape = "polygon",
          x = -240,
          y = -224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 48 },
            { x = 1008, y = 48 },
            { x = 1008, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 337,
          name = "",
          type = "",
          shape = "polygon",
          x = 528,
          y = 32,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 338,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1232,
          y = -480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = -784 },
            { x = 608, y = -784 },
            { x = 608, y = -736 },
            { x = 480, y = -736 },
            { x = 480, y = 224 },
            { x = 0, y = 224 }
          },
          properties = {}
        },
        {
          id = 339,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -816,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 192, y = -256 },
            { x = 192, y = -240 },
            { x = 0, y = -240 },
            { x = 0, y = 544 },
            { x = -16, y = 544 },
            { x = -16, y = -256 }
          },
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 343,
          name = "Bounce Ladder",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1025,
          y = -1024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 401, y = -384 },
            { x = 401, y = -368 },
            { x = 113, y = -368 },
            { x = 1, y = -272 },
            { x = 0, y = 480 },
            { x = -207, y = 480 },
            { x = -207, y = 464 },
            { x = -14.9641, y = 464 },
            { x = -15, y = -384 }
          },
          properties = {}
        },
        {
          id = 344,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1024,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 32, y = 16 },
            { x = 32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -832,
          y = -1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -32, y = 16 },
            { x = -32, y = 32 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 355,
          name = "",
          type = "",
          shape = "polygon",
          x = -1040,
          y = -544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -192, y = -16 },
            { x = -192, y = -64 },
            { x = -64, y = -64 },
            { x = -64, y = -928 },
            { x = 416, y = -928 },
            { x = 416, y = -864 },
            { x = 0, y = -864 }
          },
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1136,
          y = 2096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -32, y = -32 },
            { x = -32, y = -80 },
            { x = 0, y = -96 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1136,
          y = 1856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 320 },
            { x = 16, y = 320 },
            { x = 16, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1120,
          y = 1840,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 64 },
            { x = 0, y = 336 },
            { x = 16, y = 336 },
            { x = 16, y = 64 },
            { x = 64, y = 64 },
            { x = 64, y = 48 },
            { x = -16, y = 48 },
            { x = -16, y = 64 }
          },
          properties = {}
        },
        {
          id = 364,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1328,
          y = 1680,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 0 },
            { x = -16, y = -112 },
            { x = 0, y = -112 }
          },
          properties = {}
        },
        {
          id = 366,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1312,
          y = 1776,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1328,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 0, y = -48 },
            { x = 16, y = -48 },
            { x = 16, y = -64 },
            { x = -64, y = -64 },
            { x = -64, y = -48 },
            { x = -32, y = -48 },
            { x = -32, y = 240 },
            { x = 0, y = 240 },
            { x = 0, y = 96 },
            { x = -16, y = 96 },
            { x = -16, y = -16 }
          },
          properties = {}
        },
        {
          id = 382,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1840,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -592, y = -16 },
            { x = -592, y = -208 },
            { x = -704, y = -208 },
            { x = -704, y = 288 },
            { x = 752, y = 288 },
            { x = 752, y = -336 },
            { x = 624, y = -336 },
            { x = 640, y = -320 },
            { x = 640, y = -16 },
            { x = -96, y = -16 },
            { x = -128, y = -32 },
            { x = -256, y = -32 },
            { x = -288, y = -16 }
          },
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1968,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 496, y = -32 },
            { x = 496, y = -336 },
            { x = 512, y = -320 },
            { x = 512, y = -16 },
            { x = 480, y = -16 }
          },
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2048,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -96 },
            { x = 0, y = 96 },
            { x = 144, y = 96 },
            { x = 144, y = -96 },
            { x = 544, y = -96 },
            { x = 544, y = -80 },
            { x = 160, y = -80 },
            { x = 160, y = 96 },
            { x = 160, y = 112 },
            { x = -16, y = 112 },
            { x = -16, y = -80 },
            { x = -784, y = -80 },
            { x = -784, y = 112 },
            { x = -800, y = 112 },
            { x = -912, y = 112 },
            { x = -912, y = 96 },
            { x = -800, y = 96 },
            { x = -800, y = -96 }
          },
          properties = {}
        },
        {
          id = 388,
          name = "Bubble Intro",
          type = "Hitbox",
          shape = "polygon",
          x = 1136,
          y = -1072,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = 112, y = 112 },
            { x = 112, y = -80 },
            { x = 912, y = -80 },
            { x = 912, y = 112 },
            { x = 1056, y = 112 },
            { x = 1056, y = -80 },
            { x = 1456, y = -80 },
            { x = 1456, y = -272 },
            { x = 0, y = -272 }
          },
          properties = {}
        },
        {
          id = 389,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1264,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = -224 },
            { x = -128, y = -224 },
            { x = -128, y = -208 },
            { x = -16, y = -208 },
            { x = -16, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 1264,
          y = -944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 391 }
          }
        },
        {
          id = 391,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 1264,
          y = -816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1600,
          y = -752,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 2272,
          y = -736,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 2352,
          y = -864,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1744,
          y = -880,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = 1536,
          y = -944,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "Coin",
          shape = "point",
          x = 1648,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          type = "",
          shape = "polygon",
          x = 768,
          y = 816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 96 },
            { x = 1120, y = 96 },
            { x = 1120, y = 0 }
          },
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1232,
          y = 1475,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 112, y = 32 },
            { x = 112, y = 0 }
          },
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1136,
          y = 1555,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = 0, y = -48 },
            { x = 16, y = -48 },
            { x = 16, y = -80 },
            { x = 0, y = -80 },
            { x = 0, y = -400 },
            { x = 16, y = -400 },
            { x = 16, y = -512 },
            { x = 0, y = -512 },
            { x = 0, y = -544 },
            { x = -32, y = -544 },
            { x = -32, y = -560 },
            { x = 80, y = -560 },
            { x = 80, y = -544 },
            { x = 32, y = -544 },
            { x = 32, y = -16 }
          },
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1136,
          y = 1075,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = 80 },
            { x = 16, y = 80 },
            { x = 16, y = -32 }
          },
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1312,
          y = 1008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -208 },
            { x = 0, y = -208 },
            { x = 0, y = -512 },
            { x = 32, y = -512 },
            { x = 32, y = -528 },
            { x = -448, y = -528 },
            { x = -448, y = -512 },
            { x = -128, y = -512 },
            { x = -128, y = 1152 },
            { x = -368, y = 1152 },
            { x = -368, y = 1168 },
            { x = -112, y = 1168 },
            { x = -110.68, y = -512 },
            { x = -32, y = -512 },
            { x = -32, y = -496 },
            { x = -16, y = -496 }
          },
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1152,
          y = 768,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1264,
          y = 624,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1328,
          y = 896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -384 },
            { x = -16, y = 48 },
            { x = 16, y = 48 },
            { x = 16, y = -96 },
            { x = 0, y = -96 },
            { x = 0, y = -384 }
          },
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "",
          shape = "polygon",
          x = -1312,
          y = 944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 0 },
            { x = -32, y = 16 },
            { x = 0, y = 16 }
          },
          properties = {}
        },
        {
          id = 418,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -1384.05,
          y = 536.563,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "Bubble",
          shape = "ellipse",
          x = -1152,
          y = 496,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "",
          shape = "polygon",
          x = -224,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 80 },
            { x = 144, y = 80 },
            { x = 144, y = 480 },
            { x = 320, y = 480 },
            { x = 320, y = -192 },
            { x = 464, y = -192 },
            { x = 464, y = 704 },
            { x = 0, y = 704 }
          },
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -64,
          y = 2144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -128 },
            { x = 144, y = -128 },
            { x = 144, y = -96 },
            { x = 0, y = -96 }
          },
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -80,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -144, y = 64 },
            { x = 16, y = 64 },
            { x = 16, y = 464 },
            { x = 160, y = 464 },
            { x = 160, y = -208 },
            { x = 320, y = -208 },
            { x = 320, y = -192 },
            { x = 176, y = -192 },
            { x = 176, y = 480 },
            { x = 0, y = 480 },
            { x = 0, y = 80 },
            { x = -144, y = 80 }
          },
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 576,
          y = 1712,
          width = 0,
          height = 0,
          rotation = -180,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 144, y = 0 },
            { x = 144, y = 16 },
            { x = 0, y = 16 }
          },
          properties = {}
        },
        {
          id = 430,
          name = "",
          type = "",
          shape = "polygon",
          x = -64,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = -160, y = 0 },
            { x = -160, y = -416 },
            { x = 304, y = -416 },
            { x = 304, y = -272 },
            { x = -16, y = -272 }
          },
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -80,
          y = 1488,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -144, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = -256 },
            { x = 320, y = -256 },
            { x = 320, y = -272 },
            { x = 0, y = -272 },
            { x = 0, y = 0 },
            { x = -144, y = 0 }
          },
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "Eye",
          shape = "point",
          x = 765.711,
          y = 1607.69,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1116.53,
          y = 1446,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1211.1,
          y = 1735.81,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "Eye",
          shape = "point",
          x = 860.281,
          y = 1982.92,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "Eye",
          shape = "point",
          x = 655.888,
          y = 1897.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "Eye",
          shape = "point",
          x = 851.129,
          y = 1406.35,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1092.13,
          y = 1543.62,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1140.94,
          y = 1662.6,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "Eye",
          shape = "point",
          x = 730.08,
          y = 1742.28,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "Eye",
          shape = "point",
          x = 779.642,
          y = 1698.44,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "Eye",
          shape = "point",
          x = 751.048,
          y = 1788.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "Eye",
          shape = "point",
          x = 844.453,
          y = 1868.09,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "Eye",
          shape = "point",
          x = 825.391,
          y = 1793.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "Eye",
          shape = "point",
          x = 874.952,
          y = 1887.15,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1078.92,
          y = 1870,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1113.23,
          y = 1761.34,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1038.89,
          y = 1662.22,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "Eye",
          shape = "point",
          x = 955.013,
          y = 1589.78,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "Eye",
          shape = "point",
          x = 836.828,
          y = 1580.25,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "Eye",
          shape = "point",
          x = 876.859,
          y = 1460.16,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1004.57,
          y = 1435.38,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1019.82,
          y = 1589.78,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "Eye",
          shape = "point",
          x = 884.483,
          y = 1574.53,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "Eye",
          shape = "point",
          x = 838.734,
          y = 1483.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 484,
          name = "",
          type = "Eye",
          shape = "point",
          x = 718.643,
          y = 1528.78,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "Eye",
          shape = "point",
          x = 691.956,
          y = 1643.16,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 486,
          name = "",
          type = "Eye",
          shape = "point",
          x = 880.671,
          y = 1494.47,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 487,
          name = "",
          type = "Eye",
          shape = "point",
          x = 991.231,
          y = 1502.1,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1256.2,
          y = 1620.28,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 489,
          name = "",
          type = "Eye",
          shape = "point",
          x = 977.888,
          y = 1633.63,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "Eye",
          shape = "point",
          x = 895.921,
          y = 1620.28,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1073.2,
          y = 1711.78,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "Eye",
          shape = "point",
          x = 989.325,
          y = 1801.37,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "Eye",
          shape = "point",
          x = 996.95,
          y = 1877.62,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1107.51,
          y = 1873.81,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1023.64,
          y = 1730.84,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "Eye",
          shape = "point",
          x = 987.419,
          y = 1687,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "",
          type = "Wall",
          shape = "rectangle",
          x = 467.022,
          y = 1237.13,
          width = 909.264,
          height = 834.922,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "Eye",
          shape = "point",
          x = 800.61,
          y = 1496.38,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "Eye",
          shape = "point",
          x = 735.799,
          y = 1622.19,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "Eye",
          shape = "point",
          x = 720.549,
          y = 1717.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "Eye",
          shape = "point",
          x = 722.455,
          y = 1728.94,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "",
          type = "Eye",
          shape = "point",
          x = 798.704,
          y = 1749.9,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "",
          type = "Eye",
          shape = "point",
          x = 833.016,
          y = 1788.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 504,
          name = "",
          type = "Eye",
          shape = "point",
          x = 840.64,
          y = 1654.59,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "",
          type = "Eye",
          shape = "point",
          x = 899.733,
          y = 1669.84,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1077.01,
          y = 1700.34,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1101.79,
          y = 1793.75,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 508,
          name = "",
          type = "Eye",
          shape = "point",
          x = 827.297,
          y = 1887.15,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 509,
          name = "",
          type = "Eye",
          shape = "point",
          x = 747.236,
          y = 1866.18,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "Eye",
          shape = "point",
          x = 831.109,
          y = 1805.18,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "Eye",
          shape = "point",
          x = 932.139,
          y = 1847.12,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "Eye",
          shape = "point",
          x = 975.982,
          y = 1931,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1035.07,
          y = 1850.93,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1069.39,
          y = 1816.62,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1078.92,
          y = 1603.13,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1101.79,
          y = 1587.88,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "",
          type = "Eye",
          shape = "point",
          x = 958.826,
          y = 1513.53,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "",
          type = "Eye",
          shape = "point",
          x = 949.295,
          y = 1383.91,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1040.79,
          y = 1448.72,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1212.35,
          y = 1484.94,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1233.32,
          y = 1566.91,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1298.13,
          y = 1850.93,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1181.85,
          y = 1892.87,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "Eye",
          shape = "point",
          x = 1040.79,
          y = 1923.37,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "Eye",
          shape = "point",
          x = 743.424,
          y = 1879.53,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 526,
          name = "",
          type = "Eye",
          shape = "point",
          x = 672.894,
          y = 1809,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 527,
          name = "",
          type = "Eye",
          shape = "point",
          x = 632.863,
          y = 1704.16,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "",
          type = "Eye",
          shape = "point",
          x = 600.457,
          y = 1568.81,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "",
          type = "Eye",
          shape = "point",
          x = 615.707,
          y = 1536.41,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 271,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -240,
          y = -928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 272 }
          }
        },
        {
          id = 272,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -240,
          y = -784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "Flies",
          type = "Fireflies",
          shape = "point",
          x = 112,
          y = -704,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = "3"
          }
        },
        {
          id = 428,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -64,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 429 }
          }
        },
        {
          id = 429,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -64,
          y = 1648,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "Checkpoint",
          shape = "point",
          x = -154.909,
          y = 1597.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["is_invisible"] = false
          }
        },
        {
          id = 447,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = 96,
          y = 1232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 448 }
          }
        },
        {
          id = 448,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = 96,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "Goal",
          shape = "rectangle",
          x = -599.432,
          y = 1219.92,
          width = 233.818,
          height = 325.59,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
