return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 507,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 452,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -80,
          y = 2609.2,
          width = 1572.22,
          height = 606.803,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 1296,
          y = 3136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -447.704 },
            { x = 48, y = -447.704 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -368,
          y = 2708.29,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 52.2367 },
            { x = 0, y = 507.707 },
            { x = 2464, y = 507.707 },
            { x = 2464, y = -20.2929 },
            { x = 0, y = -20.2929 }
          },
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -158.016,
          y = 3831.86,
          width = 1288.53,
          height = 615.452,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -288,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -352, y = 0 },
            { x = -352, y = 48 },
            { x = -800, y = 48 },
            { x = -800, y = 80 },
            { x = 96, y = 80 },
            { x = 1504, y = 80 },
            { x = 1504, y = -640 },
            { x = -848, y = -656 },
            { x = -848, y = -624 },
            { x = 1472, y = -608 },
            { x = 1472, y = 48 },
            { x = 976, y = 48 },
            { x = 976, y = 0 },
            { x = 832, y = 0 },
            { x = 832, y = 48 },
            { x = 96, y = 48 },
            { x = 96, y = 0 }
          },
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = 688,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 368, y = 0 },
            { x = 391.832, y = -1.90818 },
            { x = 409.697, y = -8.10042 },
            { x = 424.627, y = -17.1573 },
            { x = 436.548, y = -34.2316 },
            { x = 443.265, y = -52.9569 },
            { x = 446.883, y = -72.263 },
            { x = 449.696, y = -94.4811 },
            { x = 450.208, y = -121.389 },
            { x = 448, y = -496 },
            { x = 442.898, y = -516.509 },
            { x = 434.308, y = -533.413 },
            { x = 419.709, y = -544.967 },
            { x = 399.312, y = -553.858 },
            { x = 379.509, y = -558.936 },
            { x = 352, y = -560 },
            { x = -1744, y = -560 },
            { x = -1744, y = -624 },
            { x = 496, y = -608 },
            { x = 496, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "polygon",
          x = 128,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1184, y = 0 },
            { x = -1216, y = 0 },
            { x = -1216, y = 608 },
            { x = -1216, y = 832 },
            { x = -1264, y = 832 },
            { x = -1264, y = -64 },
            { x = -1184, y = -64 }
          },
          properties = {}
        },
        {
          id = 478,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 479 },
            ["target"] = { id = 480 }
          }
        },
        {
          id = 479,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 481 },
            ["target"] = { id = 478 }
          }
        },
        {
          id = 481,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -1984,
          y = 3648,
          width = 1367.89,
          height = 927.963,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 400,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -1208.42,
          y = 4044.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 400,
          y = 1584,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 16,
          y = 1600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 432, y = 0 },
            { x = 928, y = 256 },
            { x = 1024, y = 256 },
            { x = 1072, y = 224 },
            { x = 1232, y = 224 },
            { x = 1232, y = 256 },
            { x = 1232, y = 320 },
            { x = 928, y = 320 },
            { x = 432, y = 64 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 429,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 960,
          y = 1856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 288, y = 0 },
            { x = 288, y = 64 },
            { x = 688, y = 64 },
            { x = 688, y = -576 },
            { x = 960, y = -576 },
            { x = 960, y = -624 },
            { x = 624, y = -624 },
            { x = 624, y = 0 }
          },
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1040,
          y = 1776,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 32 },
            { x = 208, y = 32 },
            { x = 208, y = -768 },
            { x = 0, y = -768 }
          },
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 992,
          y = 1776,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = 0 },
            { x = 32, y = 80 },
            { x = 48, y = 80 },
            { x = 96, y = 48 },
            { x = 192, y = 48 },
            { x = 192, y = 32 },
            { x = 96, y = 32 },
            { x = 48, y = 0 }
          },
          properties = {
            ["axis_x"] = 1,
            ["axis_y"] = 0
          }
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "polygon",
          x = -64,
          y = 3136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -544, y = 0 },
            { x = 2288, y = 0 },
            { x = 2288, y = 80 },
            { x = -544, y = 80 }
          },
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "BubbleField",
          shape = "polygon",
          x = 400.456,
          y = 2861.21,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 208 },
            { x = 400, y = 208 },
            { x = 400, y = 0 }
          },
          properties = {}
        },
        {
          id = 446,
          name = "Node",
          type = "AirDashNode",
          shape = "ellipse",
          x = 1024.48,
          y = 2910.5,
          width = 147.277,
          height = 147.277,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = 294.041,
          y = 2975.89,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "polygon",
          x = -64,
          y = 2608,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -544, y = 0 },
            { x = 2288, y = 0 },
            { x = 2288, y = 80 },
            { x = -544, y = 80 }
          },
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "polygon",
          x = 1344,
          y = 2688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 448 },
            { x = 112, y = 448 },
            { x = 112, y = 0 }
          },
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "polygon",
          x = -80,
          y = 4368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -256, y = 0 },
            { x = 864, y = 0 },
            { x = 864, y = 80 },
            { x = -256, y = 80 }
          },
          properties = {}
        },
        {
          id = 463,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = 400,
          y = 4336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 464 },
            ["target"] = { id = 465 }
          }
        },
        {
          id = 464,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = 256,
          y = 4336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -16,
          y = 4365.8,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 466 },
            ["target"] = { id = 463 }
          }
        },
        {
          id = 466,
          name = "",
          type = "PortalNode",
          shape = "point",
          x = -16,
          y = 4205.8,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "PathNode",
          shape = "point",
          x = -42.1072,
          y = 4165.83,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "Path",
          type = "Path",
          shape = "point",
          x = -40.9122,
          y = 4368.89,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["next"] = { id = 467 },
            ["target_01"] = { id = 465 },
            ["target_02"] = { id = 469 }
          }
        },
        {
          id = 469,
          name = "",
          type = "SlipperyMovableHitbox",
          shape = "polygon",
          x = -16,
          y = 4205.8,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 160 },
            { x = -48, y = 160 },
            { x = -48, y = 0 }
          },
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 256,
          y = 4336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 32 },
            { x = 176, y = 32 },
            { x = 144, y = 0 }
          },
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -144,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = -48, y = 48 },
            { x = 688, y = 48 },
            { x = 688, y = 0 }
          },
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -976,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 0 },
            { x = -112, y = 48 },
            { x = 336, y = 48 },
            { x = 336, y = 0 },
            { x = 336, y = -80 },
            { x = 38.7006, y = -10.5408 },
            { x = 5.73247, y = -5.12295 },
            { x = -24.4623, y = -0.804894 }
          },
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -592,
          y = 5152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 640, y = 0 },
            { x = 640, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        },
        {
          id = 493,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -496,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 494 },
            ["target"] = { id = 495 }
          }
        },
        {
          id = 494,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -608,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -224,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 496 },
            ["target"] = { id = 493 }
          }
        },
        {
          id = 496,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -384,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "polygon",
          x = -1616,
          y = 4128,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 352, y = 0 },
            { x = 352, y = 688 },
            { x = -80, y = 688 },
            { x = -80, y = -1600 },
            { x = -32, y = -1600 },
            { x = -32, y = 0 }
          },
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1648,
          y = 4096,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 16 },
            { x = 384, y = 16 },
            { x = 384, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "OneWayPlatform",
          shape = "point",
          x = -1035.25,
          y = 3787.01,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["other"] = { id = 502 }
          }
        },
        {
          id = 502,
          name = "",
          type = "OneWayPlatformNode",
          shape = "point",
          x = -907.247,
          y = 3787.01,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "Ghost",
          type = "NPC",
          shape = "point",
          x = -1392,
          y = 4016,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "on_bounce_complain",
            ["should_focus"] = true,
            ["should_lock"] = false,
            ["type"] = "eyes"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
