return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 537,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 473,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -288,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -352, y = 0 },
            { x = -352, y = 48 },
            { x = -800, y = 48 },
            { x = -800, y = 80 },
            { x = 96, y = 80 },
            { x = 1504, y = 80 },
            { x = 1504, y = -640 },
            { x = -848, y = -656 },
            { x = -848, y = -624 },
            { x = 1472, y = -608 },
            { x = 1472, y = 48 },
            { x = 976, y = 48 },
            { x = 976, y = 0 },
            { x = 832, y = 0 },
            { x = 832, y = 48 },
            { x = 96, y = 48 },
            { x = 96, y = 0 }
          },
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = 688,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 368, y = 0 },
            { x = 391.832, y = -1.90818 },
            { x = 409.697, y = -8.10042 },
            { x = 424.627, y = -17.1573 },
            { x = 436.548, y = -34.2316 },
            { x = 443.265, y = -52.9569 },
            { x = 446.883, y = -72.263 },
            { x = 449.696, y = -94.4811 },
            { x = 450.208, y = -121.389 },
            { x = 448, y = -496 },
            { x = 442.898, y = -516.509 },
            { x = 434.308, y = -533.413 },
            { x = 419.709, y = -544.967 },
            { x = 399.312, y = -553.858 },
            { x = 379.509, y = -558.936 },
            { x = 352, y = -560 },
            { x = -1744, y = -560 },
            { x = -1744, y = -624 },
            { x = 496, y = -608 },
            { x = 496, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "polygon",
          x = 128,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1184, y = 0 },
            { x = -1216, y = 0 },
            { x = -1216, y = 608 },
            { x = -1216, y = 832 },
            { x = -1264, y = 832 },
            { x = -1264, y = -64 },
            { x = -1184, y = -64 }
          },
          properties = {}
        },
        {
          id = 478,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 479 },
            ["target"] = { id = 480 }
          }
        },
        {
          id = 479,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 481 },
            ["target"] = { id = 478 }
          }
        },
        {
          id = 481,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -4246.04,
          y = 1536,
          width = 2441.34,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 474,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -144,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = -48, y = 48 },
            { x = 688, y = 48 },
            { x = 688, y = 0 }
          },
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -976,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 0 },
            { x = -112, y = 48 },
            { x = 336, y = 48 },
            { x = 336, y = 0 },
            { x = 336, y = -80 },
            { x = 38.7006, y = -10.5408 },
            { x = 5.73247, y = -5.12295 },
            { x = -24.4623, y = -0.804894 }
          },
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -592,
          y = 5152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 640, y = 0 },
            { x = 640, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        },
        {
          id = 493,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -496,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 494 },
            ["target"] = { id = 495 }
          }
        },
        {
          id = 494,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -608,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -224,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 496 },
            ["target"] = { id = 493 }
          }
        },
        {
          id = 496,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -384,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "",
          shape = "rectangle",
          x = -3516.72,
          y = 1291.71,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -3392,
          y = 2384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -320, y = 0 },
            { x = 256, y = 0 },
            { x = 256, y = -464 },
            { x = 304, y = -528 },
            { x = 352, y = -464 },
            { x = 352, y = 0 },
            { x = 1024, y = 0 },
            { x = 1024, y = 96 },
            { x = -320, y = 96 }
          },
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 2352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = -432 },
            { x = 64, y = -496 },
            { x = 112, y = -432 },
            { x = 112, y = 32 },
            { x = 160, y = 32 },
            { x = 128, y = 0 },
            { x = 128, y = -432 },
            { x = 64.7319, y = -522.145 },
            { x = 0, y = -432 }
          },
          properties = {
            ["unjumpable"] = true
          }
        },
        {
          id = 513,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3408,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 32 },
            { x = -32, y = 32 },
            { x = -32, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3264,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = 64, y = 0 },
            { x = 64, y = 48 },
            { x = -48, y = 48 }
          },
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2928,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = 64, y = 0 },
            { x = 64, y = 48 },
            { x = -48, y = 48 }
          },
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3088,
          y = 1792,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.73185, y = -6.58665 },
            { x = 54.4859, y = -80 },
            { x = 672, y = -80 },
            { x = 672, y = -96 },
            { x = 48, y = -96 },
            { x = 0, y = -32 },
            { x = -48, y = -96 },
            { x = -64, y = -96 },
            { x = -672, y = -96 },
            { x = -672, y = -80 },
            { x = -58.1452, y = -80 }
          },
          properties = {}
        },
        {
          id = 517,
          name = "Vertical Itnroduction",
          type = "Hitbox",
          shape = "polygon",
          x = -3088,
          y = 1760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = -64 },
            { x = -672, y = -64 },
            { x = -672, y = -128 },
            { x = 672, y = -128 },
            { x = 672, y = -64 },
            { x = 48, y = -64 }
          },
          properties = {}
        },
        {
          id = 518,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -3095.92,
          y = 1806.81,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["should_move_in_place"] = false
          }
        },
        {
          id = 519,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2752,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 32 },
            { x = -32, y = 32 },
            { x = -32, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 520,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -3618.54,
          y = 3248.22,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3200,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 522 },
            ["target"] = { id = 523 }
          }
        },
        {
          id = 522,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3312,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2864,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 524 },
            ["target"] = { id = 521 }
          }
        },
        {
          id = 524,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2976,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -3392,
          y = 3312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -320, y = 0 },
            { x = 256, y = 0 },
            { x = 272, y = -16 },
            { x = 272, y = -112 },
            { x = 256, y = -112 },
            { x = 256, y = -464 },
            { x = 304, y = -528 },
            { x = 352, y = -464 },
            { x = 352, y = -112 },
            { x = 336, y = -112 },
            { x = 336, y = -16 },
            { x = 352, y = 0 },
            { x = 1024, y = 0 },
            { x = 1024, y = 96 },
            { x = -320, y = 96 }
          },
          properties = {}
        },
        {
          id = 526,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 3280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -432 },
            { x = 64, y = -496 },
            { x = 112, y = -432 },
            { x = 112, y = -80 },
            { x = 128, y = -96 },
            { x = 128, y = -432 },
            { x = 64.7319, y = -522.145 },
            { x = 0, y = -432 },
            { x = 0, y = -96 },
            { x = 16, y = -80 }
          },
          properties = {
            ["unjumpable"] = true
          }
        },
        {
          id = 531,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3120,
          y = 3200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 532 },
            ["target"] = { id = 533 }
          }
        },
        {
          id = 532,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3120,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3056,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 534 },
            ["target"] = { id = 531 }
          }
        },
        {
          id = 534,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3056,
          y = 3200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = -32, y = 16 },
            { x = 16, y = 16 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 536,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3024,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 32, y = 16 },
            { x = -16, y = 16 },
            { x = -32, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
