return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 697,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 473,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -288,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -352, y = 0 },
            { x = -352, y = 48 },
            { x = -800, y = 48 },
            { x = -800, y = 80 },
            { x = 96, y = 80 },
            { x = 1504, y = 80 },
            { x = 1504, y = -640 },
            { x = -848, y = -656 },
            { x = -848, y = -624 },
            { x = 1472, y = -608 },
            { x = 1472, y = 48 },
            { x = 976, y = 48 },
            { x = 976, y = 0 },
            { x = 832, y = 0 },
            { x = 832, y = 48 },
            { x = 96, y = 48 },
            { x = 96, y = 0 }
          },
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = 688,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 368, y = 0 },
            { x = 391.832, y = -1.90818 },
            { x = 409.697, y = -8.10042 },
            { x = 424.627, y = -17.1573 },
            { x = 436.548, y = -34.2316 },
            { x = 443.265, y = -52.9569 },
            { x = 446.883, y = -72.263 },
            { x = 449.696, y = -94.4811 },
            { x = 450.208, y = -121.389 },
            { x = 448, y = -496 },
            { x = 442.898, y = -516.509 },
            { x = 434.308, y = -533.413 },
            { x = 419.709, y = -544.967 },
            { x = 399.312, y = -553.858 },
            { x = 379.509, y = -558.936 },
            { x = 352, y = -560 },
            { x = -1744, y = -560 },
            { x = -1744, y = -624 },
            { x = 496, y = -608 },
            { x = 496, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "polygon",
          x = 128,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1184, y = 0 },
            { x = -1216, y = 0 },
            { x = -1216, y = 608 },
            { x = -1216, y = 640 },
            { x = -1264, y = 640 },
            { x = -1264, y = -64 },
            { x = -1184, y = -64 }
          },
          properties = {}
        },
        {
          id = 478,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 479 },
            ["target"] = { id = 480 }
          }
        },
        {
          id = 479,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -1088,
          y = 5264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 481 },
            ["target"] = { id = 478 }
          }
        },
        {
          id = 481,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -1088,
          y = 5056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -4246.04,
          y = 1536,
          width = 2441.34,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "CameraBounds",
          shape = "rectangle",
          x = -4240,
          y = 2560,
          width = 2441.34,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 657,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -3088,
          y = 4080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -208, y = -160 },
            { x = -416, y = 48 },
            { x = -48, y = 560 },
            { x = 288, y = 560 },
            { x = 640, y = 32 },
            { x = 448, y = -160 },
            { x = 240, y = 0 }
          },
          properties = {}
        },
        {
          id = 661,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -1056,
          y = 2400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -416 },
            { x = 352, y = -416 },
            { x = 352, y = -256 },
            { x = 160, y = -256 },
            { x = 160, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 673,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -3472,
          y = 3920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 16 },
            { x = 1024, y = 16 },
            { x = 1024, y = 704 },
            { x = -32, y = 704 }
          },
          properties = {
            ["body"] = { id = 674 }
          }
        },
        {
          id = 674,
          name = "",
          type = "CameraFitBody",
          shape = "polygon",
          x = -3568,
          y = 3856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 320 },
            { x = 64, y = 320 },
            { x = 64, y = 848 },
            { x = 1120, y = 848 },
            { x = 1120, y = 336 },
            { x = 1232, y = 336 },
            { x = 1232, y = -16 },
            { x = -32, y = -16 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 474,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -144,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = -48, y = 48 },
            { x = 688, y = 48 },
            { x = 688, y = 0 }
          },
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -976,
          y = 5616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -112, y = 0 },
            { x = -112, y = 48 },
            { x = 336, y = 48 },
            { x = 336, y = 0 },
            { x = 336, y = -80 },
            { x = 38.7006, y = -10.5408 },
            { x = 5.73247, y = -5.12295 },
            { x = -24.4623, y = -0.804894 }
          },
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "AcceleratorSurface",
          shape = "polygon",
          x = -592,
          y = 5152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 640, y = 0 },
            { x = 640, y = 32 },
            { x = 0, y = 32 }
          },
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "",
          shape = "rectangle",
          x = -3516.72,
          y = 1291.71,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -3392,
          y = 2384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -320, y = 0 },
            { x = 256, y = 0 },
            { x = 256, y = -464 },
            { x = 304, y = -528 },
            { x = 352, y = -464 },
            { x = 352, y = 0 },
            { x = 1024, y = 0 },
            { x = 1024, y = 96 },
            { x = -320, y = 96 }
          },
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 2352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = -432 },
            { x = 64, y = -496 },
            { x = 112, y = -432 },
            { x = 112, y = 32 },
            { x = 160, y = 32 },
            { x = 128, y = 0 },
            { x = 128, y = -432 },
            { x = 64.7319, y = -522.145 },
            { x = 0, y = -432 }
          },
          properties = {
            ["unjumpable"] = true
          }
        },
        {
          id = 513,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3408,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 32 },
            { x = -32, y = 32 },
            { x = -32, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3264,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = 64, y = 0 },
            { x = 64, y = 48 },
            { x = -48, y = 48 }
          },
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2928,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -48, y = 0 },
            { x = 64, y = 0 },
            { x = 64, y = 48 },
            { x = -48, y = 48 }
          },
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3088,
          y = 1792,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.73185, y = -6.58665 },
            { x = 54.4859, y = -80 },
            { x = 672, y = -80 },
            { x = 672, y = -96 },
            { x = 48, y = -96 },
            { x = 0, y = -32 },
            { x = -48, y = -96 },
            { x = -64, y = -96 },
            { x = -672, y = -96 },
            { x = -672, y = -80 },
            { x = -58.1452, y = -80 }
          },
          properties = {}
        },
        {
          id = 517,
          name = "Vertical Itnroduction",
          type = "Hitbox",
          shape = "polygon",
          x = -3088,
          y = 1760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = -64 },
            { x = -672, y = -64 },
            { x = -672, y = -128 },
            { x = 672, y = -128 },
            { x = 672, y = -64 },
            { x = 48, y = -64 }
          },
          properties = {}
        },
        {
          id = 518,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -3095.92,
          y = 1806.81,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["should_move_in_place"] = false
          }
        },
        {
          id = 519,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2752,
          y = 2288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 32 },
            { x = -32, y = 32 },
            { x = -32, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 520,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -2070.52,
          y = 906.234,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3200,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 522 },
            ["target"] = { id = 523 }
          }
        },
        {
          id = 522,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3312,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2864,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 524 },
            ["target"] = { id = 521 }
          }
        },
        {
          id = 524,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2976,
          y = 2224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -3392,
          y = 3408,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -320, y = 0 },
            { x = 256, y = 0 },
            { x = 272, y = -16 },
            { x = 272, y = -112 },
            { x = 256, y = -112 },
            { x = 256, y = -464 },
            { x = 416, y = -464 },
            { x = 416, y = -112 },
            { x = 400, y = -112 },
            { x = 400, y = -16 },
            { x = 416, y = 0 },
            { x = 1088, y = 0 },
            { x = 1088, y = 288 },
            { x = -320, y = 288 }
          },
          properties = {}
        },
        {
          id = 526,
          name = "Horizontal Introduction",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 3376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -432 },
            { x = 176, y = -432 },
            { x = 176, y = -80 },
            { x = 192, y = -96 },
            { x = 192, y = -448 },
            { x = 0, y = -448 },
            { x = 0, y = -96 },
            { x = 16, y = -80 }
          },
          properties = {
            ["unjumpable"] = true
          }
        },
        {
          id = 531,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3120,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 532 },
            ["target"] = { id = 533 }
          }
        },
        {
          id = 532,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3120,
          y = 3392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2992,
          y = 3392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 534 },
            ["target"] = { id = 531 }
          }
        },
        {
          id = 534,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2992,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3152,
          y = 3392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 0 },
            { x = -32, y = 16 },
            { x = 16, y = 16 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 536,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3024,
          y = 3392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 80, y = 0 },
            { x = 96, y = 16 },
            { x = 48, y = 16 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 616,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -464,
          y = 5936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 64, y = 32 },
            { x = 48, y = 64 },
            { x = -16, y = 32 }
          },
          properties = {}
        },
        {
          id = 617,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -400,
          y = 5888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 48 },
            { x = 48, y = 48 },
            { x = 32, y = -16 },
            { x = -16, y = -32 }
          },
          properties = {}
        },
        {
          id = 618,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -448,
          y = 5888,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -64, y = 48 },
            { x = -96, y = 32 },
            { x = -16, y = -48 }
          },
          properties = {}
        },
        {
          id = 619,
          name = "",
          type = "DoubleJumpTether",
          shape = "point",
          x = -544,
          y = 5504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 620,
          name = "",
          type = "DoubleJumpTether",
          shape = "point",
          x = -288,
          y = 5456,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 621,
          name = "",
          type = "DoubleJumpTether",
          shape = "point",
          x = -256,
          y = 5536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "",
          shape = "polygon",
          x = -3568,
          y = 4576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 368, y = -32 },
            { x = 368, y = -16 },
            { x = 480, y = -16 },
            { x = 496, y = -16 },
            { x = 496, y = -288 },
            { x = 384, y = -288 },
            { x = 448, y = -352 },
            { x = 496, y = -352 },
            { x = 496, y = -496 },
            { x = 544, y = -496 },
            { x = 608, y = -496 },
            { x = 608, y = -448 },
            { x = 544, y = -448 },
            { x = 544, y = 16 },
            { x = 608, y = 16 },
            { x = 608, y = 128 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 635,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3008,
          y = 4032,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 112 },
            { x = 0, y = 544 },
            { x = 80, y = 544 },
            { x = 80, y = 112 },
            { x = 40.1221, y = 112 },
            { x = 40.1221, y = 96 },
            { x = 96, y = 96 },
            { x = 96, y = 560 },
            { x = -16, y = 560 },
            { x = -16, y = 96 },
            { x = 40.1221, y = 96 },
            { x = 40.1221, y = 112 }
          },
          properties = {}
        },
        {
          id = 637,
          name = "",
          type = "",
          shape = "polygon",
          x = -3168,
          y = 4176,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -128, y = -128 },
            { x = -176, y = -176 },
            { x = -240, y = -112 },
            { x = -192, y = -64 }
          },
          properties = {}
        },
        {
          id = 642,
          name = "",
          type = "",
          shape = "polygon",
          x = -2368,
          y = 4576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = -368, y = -32 },
            { x = -368, y = -16 },
            { x = -496, y = -16 },
            { x = -496, y = -288 },
            { x = -384, y = -288 },
            { x = -448, y = -352 },
            { x = -496, y = -352 },
            { x = -496, y = -496 },
            { x = -544, y = -496 },
            { x = -608, y = -496 },
            { x = -608, y = -448 },
            { x = -544, y = -448 },
            { x = -544, y = 16 },
            { x = -608, y = 16 },
            { x = -608, y = 128 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 647,
          name = "",
          type = "",
          shape = "polygon",
          x = -2768,
          y = 4176,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = -128 },
            { x = 176, y = -176 },
            { x = 240, y = -112 },
            { x = 192, y = -64 }
          },
          properties = {}
        },
        {
          id = 648,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3184,
          y = 4288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = 96, y = 16 },
            { x = 96, y = 160 },
            { x = 112, y = 160 },
            { x = 112, y = 0 }
          },
          properties = {}
        },
        {
          id = 649,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3120,
          y = 4224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 48, y = -144 },
            { x = 256, y = -144 },
            { x = 256, y = 0 },
            { x = 304, y = 0 },
            { x = 288, y = -16 },
            { x = 272, y = -16 },
            { x = 272, y = -160 },
            { x = 32, y = -160 },
            { x = 32, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 651,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2864,
          y = 4448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -8.29883 },
            { x = 16, y = -18.2089 },
            { x = 16, y = -144 },
            { x = 128, y = -144 },
            { x = 112, y = -160 },
            { x = 0, y = -160 }
          },
          properties = {}
        },
        {
          id = 652,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3424,
          y = 4048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 16 },
            { x = 48, y = 80 },
            { x = 64, y = 64 },
            { x = 16, y = 16 },
            { x = 80, y = -48 },
            { x = 128, y = 0 },
            { x = 144, y = -16 },
            { x = 80, y = -80 }
          },
          properties = {}
        },
        {
          id = 653,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2512,
          y = 4048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 16 },
            { x = -48, y = 80 },
            { x = -64, y = 64 },
            { x = -16, y = 16 },
            { x = -80, y = -48 },
            { x = -128, y = 0 },
            { x = -144, y = -16 },
            { x = -80, y = -80 }
          },
          properties = {}
        },
        {
          id = 654,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -3200,
          y = 4544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 128, y = 16 },
            { x = 128, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 655,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -2864,
          y = 4544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 128, y = 16 },
            { x = 128, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 663,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = -688,
          y = 832,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 665,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = -1648,
          y = 1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -144, y = 0 },
            { x = 272, y = 0 },
            { x = 272, y = 32 },
            { x = -144, y = 32 }
          },
          properties = {}
        },
        {
          id = 666,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1776,
          y = 1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = 32 },
            { x = -32, y = 32 },
            { x = -32, y = -96 },
            { x = -208, y = -96 },
            { x = -208, y = -112 },
            { x = -16, y = -112 }
          },
          properties = {}
        },
        {
          id = 667,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1456,
          y = 1072,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 96, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = -128 },
            { x = 878.826, y = -128 },
            { x = 880, y = -416 },
            { x = 1520, y = -416 },
            { x = 1520, y = -928 },
            { x = 2096, y = -928 },
            { x = 2096, y = -1056 },
            { x = 2112, y = -1056 },
            { x = 2112, y = -1296 },
            { x = 2096, y = -1296 },
            { x = 2096, y = -1648 },
            { x = 1856, y = -1648 },
            { x = 1856, y = -2336 },
            { x = 1408, y = -2336 },
            { x = 1408, y = -2352 },
            { x = 1872, y = -2352 },
            { x = 1872, y = -1664 },
            { x = 2128, y = -1664 },
            { x = 2128, y = -1648 },
            { x = 2128, y = -912 },
            { x = 1536, y = -912 },
            { x = 1536, y = -400 },
            { x = 896, y = -400 },
            { x = 896, y = -128 },
            { x = 896, y = -112 },
            { x = 96, y = -112 }
          },
          properties = {}
        },
        {
          id = 668,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = -1584,
          y = 928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 669,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1984,
          y = 784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = -16 },
            { x = 1232, y = -16 },
            { x = 1232, y = -304 },
            { x = 1872, y = -304 },
            { x = 1872, y = -816.89 },
            { x = 2448, y = -816 },
            { x = 2448, y = -1184 },
            { x = 2208, y = -1184 },
            { x = 2208, y = -1295.73 },
            { x = 2192, y = -1296 },
            { x = 2192, y = -1504 },
            { x = 2208, y = -1504 },
            { x = 2208, y = -1712 },
            { x = 2192, y = -1712 },
            { x = 2192, y = -1840 },
            { x = 2208, y = -1840 },
            { x = 2208, y = -1872 },
            { x = 1936, y = -1872 },
            { x = 1936, y = -1856 },
            { x = 2176, y = -1856 },
            { x = 2176, y = -1561.08 },
            { x = 2176, y = -1168 },
            { x = 2432, y = -1168 },
            { x = 2432, y = -832 },
            { x = 1856, y = -832 },
            { x = 1856, y = -320 },
            { x = 1216, y = -320 },
            { x = 1216, y = -32 },
            { x = 32, y = -32 }
          },
          properties = {}
        },
        {
          id = 677,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = -32,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 678,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = -32,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 679,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = -32,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 685,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = 608,
          y = -16,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 687,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 640,
          y = -256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 0, y = 272 },
            { x = 16, y = 272 },
            { x = 16, y = 32 }
          },
          properties = {}
        },
        {
          id = 689,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 208,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = 176 },
            { x = 16, y = 176 },
            { x = 16, y = -32 }
          },
          properties = {}
        },
        {
          id = 690,
          name = "",
          type = "",
          shape = "polygon",
          x = 224,
          y = -816,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -112 },
            { x = -16, y = -112 },
            { x = -16, y = -240 },
            { x = 0, y = -240 }
          },
          properties = {}
        },
        {
          id = 691,
          name = "Tether",
          type = "DoubleJumpTether",
          shape = "point",
          x = 256,
          y = -544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 694,
          name = "",
          type = "",
          shape = "polygon",
          x = 736,
          y = -1120,
          width = 0,
          height = 0,
          rotation = 180,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 176 },
            { x = 16, y = 176 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 695,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -144,
          y = -48,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 224, y = 0 },
            { x = 224, y = 720 },
            { x = 16, y = 720 }
          },
          properties = {}
        },
        {
          id = 696,
          name = "",
          type = "CameraFit",
          shape = "polygon",
          x = -768,
          y = 464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 496 },
            { x = 208, y = 496 },
            { x = 208, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 627,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3072,
          y = 4448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 628 },
            ["target"] = { id = 629 }
          }
        },
        {
          id = 628,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3072,
          y = 4544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 629,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3008,
          y = 4144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 630 },
            ["target"] = { id = 627 }
          }
        },
        {
          id = 630,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2928,
          y = 4144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 631,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2928,
          y = 4576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 632 },
            ["target"] = { id = 633 }
          }
        },
        {
          id = 632,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3008,
          y = 4576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 633,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3120,
          y = 4224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 634 },
            ["target"] = { id = 631 }
          }
        },
        {
          id = 634,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3184,
          y = 4288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 638,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2752,
          y = 4288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 639 },
            ["target"] = { id = 640 }
          }
        },
        {
          id = 639,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2816,
          y = 4224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 640,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -3360,
          y = 4112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 641 },
            ["target"] = { id = 638 }
          }
        },
        {
          id = 641,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -3296,
          y = 4048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 643,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2864,
          y = 4544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 644 },
            ["target"] = { id = 645 }
          }
        },
        {
          id = 644,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2864,
          y = 4448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 645,
          name = "Portal",
          type = "Portal",
          shape = "point",
          x = -2640,
          y = 4048,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["left_or_right"] = false,
            ["other"] = { id = 646 },
            ["target"] = { id = 643 }
          }
        },
        {
          id = 646,
          name = "Portal",
          type = "PortalNode",
          shape = "point",
          x = -2576,
          y = 4112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
