return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 421,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 388,
          name = "Wall Jump 02",
          type = "Hitbox",
          shape = "polygon",
          x = 1664,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 16 },
            { x = 16, y = -96 },
            { x = 0, y = -112 },
            { x = 0, y = -192 },
            { x = 16, y = -208 },
            { x = 16, y = -272 },
            { x = 0, y = -288 },
            { x = 0, y = -368 },
            { x = 16, y = -384 },
            { x = 16, y = -448 },
            { x = 0, y = -464 },
            { x = 0, y = -544 },
            { x = 16, y = -560 },
            { x = 16, y = -608 },
            { x = 64, y = -608 },
            { x = 80, y = -624 },
            { x = 80, y = -592 },
            { x = 80, y = 48 },
            { x = -384, y = 48 },
            { x = -384, y = 0 },
            { x = -144, y = 0 },
            { x = -128, y = 16 },
            { x = -16, y = 16 }
          },
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1520,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 144, y = 0 },
            { x = 144, y = -112 },
            { x = 160, y = -96 },
            { x = 160, y = 16 },
            { x = 128, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 391,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 64 },
            { x = 0, y = 160 },
            { x = 16, y = 144 },
            { x = 16, y = 80 }
          },
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 96 },
            { x = 0, y = 192 },
            { x = 16, y = 176 },
            { x = 16, y = 112 }
          },
          properties = {}
        },
        {
          id = 394,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 0, y = -48 },
            { x = 80, y = -48 },
            { x = 64, y = -32 },
            { x = 16, y = -32 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2292.07,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 16 },
            { x = 16, y = -96 },
            { x = 0, y = -112 },
            { x = 0, y = -192 },
            { x = 16, y = -208 },
            { x = 16, y = -368 },
            { x = 0, y = -384 },
            { x = 0, y = -480 },
            { x = 16, y = -496 },
            { x = 16, y = -672 },
            { x = 64, y = -672 },
            { x = 80, y = -688 },
            { x = 80, y = -656 },
            { x = 80, y = 48 },
            { x = -384, y = 48 },
            { x = -384, y = 0 },
            { x = -32, y = 0 },
            { x = -16, y = 16 }
          },
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2148.07,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 112, y = 0 },
            { x = 144, y = 0 },
            { x = 144, y = -112 },
            { x = 160, y = -96 },
            { x = 160, y = 16 },
            { x = 128, y = 16 },
            { x = 128, y = 16 }
          },
          properties = {}
        },
        {
          id = 397,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2288,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 4.066, y = -32 },
            { x = 4.066, y = 160 },
            { x = 20.066, y = 144 },
            { x = 20.066, y = -16 }
          },
          properties = {}
        },
        {
          id = 399,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2288,
          y = 96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 4.066, y = 96 },
            { x = 4.066, y = -112 },
            { x = 84.066, y = -112 },
            { x = 68.066, y = -96 },
            { x = 20.066, y = -96 },
            { x = 20.066, y = 80 }
          },
          properties = {}
        },
        {
          id = 400,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = 147.999,
          y = 537.049,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "Wall Jump 03",
          type = "",
          shape = "polygon",
          x = 2100.07,
          y = 528,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -191.669 },
            { x = -16, y = -208 },
            { x = -16, y = -368 },
            { x = 0, y = -384 },
            { x = 0, y = -496 },
            { x = -16.4272, y = -512 },
            { x = -64, y = -512 },
            { x = -64, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 403,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2084.07,
          y = 176,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -32 },
            { x = 16, y = 160 },
            { x = 0, y = 144 },
            { x = 0, y = -16 }
          },
          properties = {}
        },
        {
          id = 404,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2100.07,
          y = 64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 0, y = -189.391 },
            { x = 48, y = -240 },
            { x = 288, y = -240 },
            { x = 288, y = -272 },
            { x = -64, y = -272 },
            { x = -64, y = -48 },
            { x = -16, y = -48 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "Coin",
          shape = "point",
          x = 2132.07,
          y = -144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1839.28,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.0850234, y = -128.47 },
            { x = 16.085, y = -112.47 },
            { x = 16, y = 80 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 409,
          name = "First Walljump",
          type = "Hitbox",
          shape = "polygon",
          x = 1648,
          y = 1808,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 31.2841, y = -480 },
            { x = 191.284, y = -480 },
            { x = 207.284, y = -464 },
            { x = 207.369, y = -656.47 },
            { x = 191.369, y = -672.47 },
            { x = 431.369, y = -672.47 },
            { x = 431.284, y = -448 },
            { x = 111.284, y = -448 },
            { x = 111.284, y = 112 },
            { x = -400.716, y = 112 },
            { x = -400.716, y = -16 },
            { x = -352.716, y = -16 },
            { x = -352.716, y = 48 },
            { x = 79.2841, y = 48 },
            { x = 79.2841, y = 16 },
            { x = 79.2841, y = -303.776 },
            { x = 71.448, y = -320 },
            { x = 63.2841, y = -303.776 },
            { x = 63.2841, y = 32 },
            { x = -336.716, y = 32 },
            { x = -336.716, y = 0 },
            { x = -320.716, y = 0 },
            { x = 31.2841, y = 0 }
          },
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 1680,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 47.2841, y = -175.671 },
            { x = 47.2841, y = 160 },
            { x = -352.716, y = 160 },
            { x = -352.716, y = 128 },
            { x = -336.716, y = 128 },
            { x = -336.716, y = 80 },
            { x = -352.716, y = 80 },
            { x = -384.716, y = 96 },
            { x = -416.716, y = 96 },
            { x = -416.716, y = 112 },
            { x = -368.716, y = 112 },
            { x = -368.716, y = 176 },
            { x = 63.2841, y = 176 },
            { x = 63.2841, y = -175.671 },
            { x = 55.8999, y = -192 }
          },
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1312,
          y = 1752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -8 },
            { x = -32, y = -24 },
            { x = -64, y = -24 },
            { x = -64, y = -40 },
            { x = -0.63091, y = -40.4704 },
            { x = -0.63091, y = -392.47 },
            { x = 15.3691, y = -392.47 },
            { x = 16, y = -40 },
            { x = 16, y = -8 }
          },
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1248,
          y = 1728,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 64, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 32 },
            { x = 64, y = 32 },
            { x = 32, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {
            ["axis_x"] = 1,
            ["render_priority"] = -10
          }
        },
        {
          id = 414,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1296,
          y = 1712,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 15.3691, y = -0.470433 },
            { x = -48.7159, y = 0 },
            { x = -48, y = -512 },
            { x = 32, y = -512 },
            { x = 31.3691, y = -352.47 },
            { x = 15.3691, y = -352.47 }
          },
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1701.02,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -5.65047, y = 47.5296 },
            { x = -21.6505, y = 31.5296 },
            { x = -21.0191, y = -304 },
            { x = -277.019, y = -304 },
            { x = -277.019, y = -336 },
            { x = 0, y = -336 }
          },
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1695.37,
          y = 1215.53,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -31.3691, y = -15.53 },
            { x = -31.3691, y = -31.53 },
            { x = -95.3691, y = -95.53 },
            { x = -303.369, y = -95.53 },
            { x = -367.369, y = -31.53 },
            { x = -367.369, y = -15.53 },
            { x = -447.369, y = -15.53 },
            { x = -447.369, y = -367.53 },
            { x = -272, y = -368 },
            { x = -16, y = -368 },
            { x = -16, y = -32 }
          },
          properties = {}
        },
        {
          id = 419,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 1360,
          y = 1232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "",
          shape = "polygon",
          x = 96,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 112, y = 0 },
            { x = 112, y = 64 },
            { x = 736, y = 64 },
            { x = 736, y = 0 },
            { x = 976, y = 0 },
            { x = 976, y = 80 },
            { x = 0, y = 80 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
