return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 615,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 388,
          name = "Wall Jump 02",
          type = "Hitbox",
          shape = "polygon",
          x = 1664,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 16, y = -112 },
            { x = 0, y = -128 },
            { x = 0, y = -208 },
            { x = 16, y = -224 },
            { x = 16, y = -272 },
            { x = 0, y = -288 },
            { x = 0, y = -512 },
            { x = 16, y = -528 },
            { x = 16, y = -576 },
            { x = 0, y = -592 },
            { x = 0, y = -656 },
            { x = 80, y = -656 },
            { x = 80, y = 48 },
            { x = -384, y = 48 },
            { x = -384, y = -16 },
            { x = -48, y = -16 },
            { x = -32, y = 0 }
          },
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2292.07,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -4.07, y = 0 },
            { x = -4.07, y = -112 },
            { x = 11.93, y = -128 },
            { x = 11.93, y = -224 },
            { x = -4.07, y = -240 },
            { x = -4.07, y = -416 },
            { x = 11.93, y = -432 },
            { x = 11.93, y = -528 },
            { x = -4.07, y = -544 },
            { x = -4.07, y = -704 },
            { x = 59.934, y = -704 },
            { x = 59.93, y = 48 },
            { x = -4.07, y = 48 }
          },
          properties = {}
        },
        {
          id = 400,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -1696,
          y = -662.64,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2100.79,
          y = 527.284,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -4.78582, y = 0.71582 },
            { x = -4.78582, y = -127.284 },
            { x = -20.7858, y = -143.284 },
            { x = -20.7858, y = -239.284 },
            { x = -4.78582, y = -255.284 },
            { x = -4.78582, y = -447.284 },
            { x = -20.7858, y = -463.284 },
            { x = -20.7858, y = -559.284 },
            { x = -4.07, y = -576 },
            { x = -4.78582, y = -575.284 },
            { x = -4.78582, y = -671.284 },
            { x = 43.2142, y = -719.284 },
            { x = 283.93, y = -720 },
            { x = 283.93, y = -752 },
            { x = -68.7858, y = -751.284 },
            { x = -68.7858, y = 0.71582 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "Coin",
          shape = "point",
          x = 2132.07,
          y = -144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1839.28,
          y = 1264,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.0850234, y = -128.47 },
            { x = 16.085, y = -112.47 },
            { x = 16, y = 80 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 409,
          name = "First Walljump",
          type = "Hitbox",
          shape = "polygon",
          x = 1648,
          y = 1808,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 31.2841, y = -480 },
            { x = 191.284, y = -480 },
            { x = 207.284, y = -464 },
            { x = 207.369, y = -656.47 },
            { x = 191.369, y = -672.47 },
            { x = 431.369, y = -672.47 },
            { x = 431.284, y = -448 },
            { x = 111.284, y = -448 },
            { x = 111.284, y = 112 },
            { x = -400.716, y = 112 },
            { x = -400.716, y = -16 },
            { x = -352.716, y = -16 },
            { x = -352.716, y = 48 },
            { x = 79.2841, y = 48 },
            { x = 79.2841, y = 16 },
            { x = 79.2841, y = -303.776 },
            { x = 71.448, y = -320 },
            { x = 63.2841, y = -303.776 },
            { x = 63.2841, y = 32 },
            { x = -336.716, y = 32 },
            { x = -336.716, y = 0 },
            { x = -320.716, y = 0 },
            { x = 31.2841, y = 0 }
          },
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 1680,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 47.2841, y = -175.671 },
            { x = 47.2841, y = 160 },
            { x = -352.716, y = 160 },
            { x = -352.716, y = 128 },
            { x = -336.716, y = 128 },
            { x = -336.716, y = 80 },
            { x = -352.716, y = 80 },
            { x = -384.716, y = 96 },
            { x = -416.716, y = 96 },
            { x = -416.716, y = 112 },
            { x = -368.716, y = 112 },
            { x = -368.716, y = 176 },
            { x = 63.2841, y = 176 },
            { x = 63.2841, y = -175.671 },
            { x = 55.8999, y = -192 }
          },
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1312,
          y = 1752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -8 },
            { x = -32, y = -24 },
            { x = -64, y = -24 },
            { x = -64, y = -40 },
            { x = -0.63091, y = -40.4704 },
            { x = -0.63091, y = -392.47 },
            { x = 15.3691, y = -392.47 },
            { x = 16, y = -40 },
            { x = 16, y = -8 }
          },
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1248,
          y = 1728,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 64, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 32 },
            { x = 64, y = 32 },
            { x = 32, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {
            ["axis_x"] = 1,
            ["render_priority"] = -10
          }
        },
        {
          id = 414,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1296,
          y = 1712,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 15.3691, y = -0.470433 },
            { x = -48.7159, y = 0 },
            { x = -48, y = -512 },
            { x = 32, y = -512 },
            { x = 31.3691, y = -352.47 },
            { x = 15.3691, y = -352.47 }
          },
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1701.02,
          y = 1152,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -5.65047, y = 47.5296 },
            { x = -21.6505, y = 31.5296 },
            { x = -21.0191, y = -304 },
            { x = -277.019, y = -304 },
            { x = -277.019, y = -336 },
            { x = 0, y = -336 }
          },
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1695.37,
          y = 1215.53,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -31.3691, y = -15.53 },
            { x = -31.3691, y = -31.53 },
            { x = -95.3691, y = -95.53 },
            { x = -303.369, y = -95.53 },
            { x = -367.369, y = -31.53 },
            { x = -367.369, y = -15.53 },
            { x = -447.369, y = -15.53 },
            { x = -447.369, y = -367.53 },
            { x = -272, y = -368 },
            { x = -16, y = -368 },
            { x = -16, y = -32 }
          },
          properties = {}
        },
        {
          id = 419,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 1360,
          y = 1232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "Platform 01",
          type = "Hitbox",
          shape = "polygon",
          x = -1568,
          y = -656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 96, y = 16 },
            { x = 96, y = 208 },
            { x = 2957.9, y = 208 },
            { x = 2960, y = -368 },
            { x = 2928, y = -400 },
            { x = 3136, y = -400 },
            { x = 3136, y = 208 },
            { x = 3136, y = 240 },
            { x = 0, y = 240 }
          },
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2288,
          y = 432,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 534,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2096,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 112 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2288,
          y = 128,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2096,
          y = -48,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 112 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 539,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2288,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = -384, y = 64 },
            { x = -384, y = 0 }
          },
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2672,
          y = -48,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = -384, y = 16 },
            { x = -384, y = 0 }
          },
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 543,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 624,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 608,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 528,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 554,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 432,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 416,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 559,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 560,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 352,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 563,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 565,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1776,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1776,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 80 },
            { x = 16, y = 64 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 573,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 208,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -128 },
            { x = 0, y = -48 },
            { x = 16, y = -64 },
            { x = 16, y = -112 }
          },
          properties = {}
        },
        {
          id = 574,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1664,
          y = 544,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 112 },
            { x = -48, y = 112 },
            { x = -32, y = 128 },
            { x = 16, y = 128 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 575,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2496,
          y = 976,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -576 },
            { x = 0, y = 528 },
            { x = -16, y = 544 },
            { x = -32, y = 544 },
            { x = -32, y = -576 }
          },
          properties = {}
        },
        {
          id = 576,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2544,
          y = 976,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -576 },
            { x = 32, y = -576 },
            { x = 32, y = 544 },
            { x = 16, y = 544 },
            { x = 0, y = 528 }
          },
          properties = {}
        },
        {
          id = 577,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2496,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -144, y = 16 },
            { x = -144, y = 48 },
            { x = -64, y = 48 },
            { x = -48, y = 64 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 578,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2544,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 96 },
            { x = -16, y = 112 },
            { x = -48, y = 112 },
            { x = -48, y = 144 },
            { x = 32, y = 144 },
            { x = 32, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 579,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2496,
          y = 1616,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = -208, y = 32 },
            { x = -208, y = 0 }
          },
          properties = {}
        },
        {
          id = 580,
          name = "Chimney",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2496,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -32, y = 0 },
            { x = -32, y = -160 },
            { x = 256, y = -160 },
            { x = 256, y = -128 },
            { x = 32, y = -128 },
            { x = 0, y = -104 }
          },
          properties = {}
        },
        {
          id = 581,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2544,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -32 },
            { x = 64, y = -32 },
            { x = 80, y = -16 },
            { x = 80, y = 0 }
          },
          properties = {}
        },
        {
          id = 582,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2608,
          y = 368,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 144, y = 0 },
            { x = 144, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 583,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 2496,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 48, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {
            ["axis_y"] = -1,
            ["render_priority"] = -1,
            ["velocity"] = 0.25
          }
        },
        {
          id = 584,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1248,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 64, y = 16 },
            { x = 224, y = 16 },
            { x = 240, y = 0 }
          },
          properties = {}
        },
        {
          id = 585,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -832,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 64, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 0 }
          },
          properties = {}
        },
        {
          id = 586,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -560,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 224, y = 16 },
            { x = 304, y = 16 },
            { x = 320, y = 0 }
          },
          properties = {}
        },
        {
          id = 587,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1456,
          y = -560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -80 },
            { x = 16, y = -80 },
            { x = 16, y = -48 },
            { x = 48, y = -48 },
            { x = 48, y = -16 },
            { x = 80, y = -16 },
            { x = 80, y = 16 },
            { x = 112, y = 16 },
            { x = 112, y = 48 },
            { x = 144, y = 48 },
            { x = 144, y = 80 },
            { x = 2816, y = 80 },
            { x = 2816, y = -432 },
            { x = 2769.36, y = -479.677 },
            { x = 2768, y = -496 },
            { x = 2816, y = -496 },
            { x = 2848, y = -464 },
            { x = 2848, y = 112 },
            { x = -16, y = 112 }
          },
          properties = {}
        },
        {
          id = 590,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1008,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = -192, y = 32 },
            { x = -192, y = 0 },
            { x = -176, y = 16 },
            { x = -16, y = 16 }
          },
          properties = {}
        },
        {
          id = 591,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -784,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 240, y = 32 },
            { x = 240, y = 0 },
            { x = 224, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 592,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -352,
          y = -688,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 112, y = 32 },
            { x = 112, y = 0 },
            { x = 96, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 593,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -320,
          y = -784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 224, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 0 }
          },
          properties = {}
        },
        {
          id = 594,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -112,
          y = -784,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 80, y = 32 },
            { x = 80, y = 0 },
            { x = 64, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 596,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -96,
          y = -848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 176, y = -16 },
            { x = 176, y = 32 },
            { x = 208, y = 32 },
            { x = 224, y = 16 },
            { x = 640, y = 16 },
            { x = 752, y = 16 },
            { x = 768, y = 32 },
            { x = 784, y = 32 },
            { x = 784, y = -256 },
            { x = 640, y = -256 },
            { x = 640, y = -176 },
            { x = 544, y = -96 },
            { x = 544, y = 0 },
            { x = 224, y = 0 },
            { x = 210.274, y = -16 }
          },
          properties = {}
        },
        {
          id = 597,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 112,
          y = -848,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 560, y = 32 },
            { x = 544, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 599,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -1248,
          y = -512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 48, y = 32 },
            { x = 2608, y = 32 },
            { x = 2608, y = 0 }
          },
          properties = {
            ["axis_x"] = -1,
            ["velocity"] = 1.5
          }
        },
        {
          id = 601,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -208,
          y = -992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 96, y = 32 },
            { x = 112, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 32 },
            { x = 288, y = 0 },
            { x = 128, y = 0 },
            { x = 112, y = -16 },
            { x = 96, y = -16 }
          },
          properties = {}
        },
        {
          id = 602,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 304,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 176, y = -80 },
            { x = 240, y = -48 },
            { x = 240, y = -64 },
            { x = 384, y = -64 },
            { x = 384, y = -48 },
            { x = 448, y = -80 },
            { x = 400, y = -80 },
            { x = 384, y = -96 },
            { x = 240, y = -96 },
            { x = 224, y = -80 }
          },
          properties = {}
        },
        {
          id = 603,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 720,
          y = -1056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 0 },
            { x = 128, y = 48 },
            { x = 576, y = 48 },
            { x = 576, y = 0 }
          },
          properties = {
            ["axis_y"] = -1,
            ["render_priority"] = -200
          }
        },
        {
          id = 604,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 928,
          y = -1088,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 144 },
            { x = 144, y = 160 },
            { x = 160, y = 144 },
            { x = 159.608, y = 27.6825 },
            { x = 127.608, y = 27.6825 }
          },
          properties = {}
        },
        {
          id = 608,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 128,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 32 },
            { x = 224, y = 32 },
            { x = 208, y = 16 },
            { x = 144, y = 16 }
          },
          properties = {}
        },
        {
          id = 609,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -80,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 336, y = 0 },
            { x = 336, y = 32 },
            { x = 352, y = 16 },
            { x = 416, y = 16 },
            { x = 432, y = 32 },
            { x = 432, y = -48 }
          },
          properties = {}
        },
        {
          id = 611,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 688,
          y = -1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 612,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 320,
          y = -1136,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = 16 },
            { x = 208, y = 16 },
            { x = 224, y = 0 },
            { x = 144, y = 0 }
          },
          properties = {}
        },
        {
          id = 614,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -112,
          y = -960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 192, y = 0 },
            { x = 176, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 610,
          name = "NPC",
          type = "NPC",
          shape = "point",
          x = 512,
          y = -896,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "slippery_floor_tutorial",
            ["type"] = "eyes"
          }
        },
        {
          id = 613,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 512,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
