return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 693,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "aux2",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 687,
          name = "Control Trigger",
          type = "ControlIndicatorTrigger",
          shape = "rectangle",
          x = -416,
          y = 2336,
          width = 1216,
          height = 771.219,
          rotation = 0,
          visible = true,
          properties = {
            ["type"] = "SLIDE"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 650,
          name = "Fit",
          type = "CameraFit",
          shape = "rectangle",
          x = -1314.05,
          y = 1199.92,
          width = 1165.24,
          height = 655.449,
          rotation = 0,
          visible = true,
          properties = {
            ["speed"] = -5
          }
        },
        {
          id = 674,
          name = "Fit",
          type = "CameraFit",
          shape = "rectangle",
          x = -560,
          y = 2240,
          width = 1506.53,
          height = 847.426,
          rotation = 0,
          visible = true,
          properties = {
            ["focus"] = { id = 682 }
          }
        },
        {
          id = 682,
          name = "Focus",
          type = "CameraFitFocus",
          shape = "point",
          x = 192,
          y = 2640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 388,
          name = "Wall Jump 02",
          type = "Hitbox",
          shape = "polygon",
          x = 1656.83,
          y = 669.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = 0 },
            { x = 16, y = -112 },
            { x = 0, y = -128 },
            { x = 0, y = -208 },
            { x = 16, y = -224 },
            { x = 16, y = -272 },
            { x = 0, y = -288 },
            { x = 0, y = -512 },
            { x = 16, y = -528 },
            { x = 16, y = -576 },
            { x = 0, y = -592 },
            { x = 0, y = -656 },
            { x = 80, y = -656 },
            { x = 80, y = 48 },
            { x = -384, y = 48 },
            { x = -384, y = -16 },
            { x = -48, y = -16 },
            { x = -32, y = 0 }
          },
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2284.9,
          y = 669.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -4.07, y = 0 },
            { x = -4.07, y = -112 },
            { x = 11.93, y = -128 },
            { x = 11.93, y = -224 },
            { x = -4.07, y = -240 },
            { x = -4.07, y = -416 },
            { x = 11.93, y = -432 },
            { x = 11.93, y = -528 },
            { x = -4.07, y = -544 },
            { x = -4.07, y = -704 },
            { x = 59.934, y = -704 },
            { x = 59.93, y = 48 },
            { x = -4.07, y = 48 }
          },
          properties = {}
        },
        {
          id = 400,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = -722.418,
          y = 2311.9,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "Wall Jump 03",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2093.62,
          y = 524.526,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -4.78582, y = 0.71582 },
            { x = -4.78582, y = -127.284 },
            { x = -20.7858, y = -143.284 },
            { x = -20.7858, y = -239.284 },
            { x = -4.78582, y = -255.284 },
            { x = -4.78582, y = -447.284 },
            { x = -20.7858, y = -463.284 },
            { x = -20.7858, y = -559.284 },
            { x = -4.07, y = -576 },
            { x = -4.78582, y = -575.284 },
            { x = -4.78582, y = -671.284 },
            { x = 43.2142, y = -719.284 },
            { x = 283.93, y = -720 },
            { x = 283.93, y = -752 },
            { x = -68.7858, y = -751.284 },
            { x = -68.7858, y = 0.71582 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "Coin",
          shape = "point",
          x = 2124.9,
          y = -146.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1832.11,
          y = 1261.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.0850234, y = -128.47 },
            { x = 16.085, y = -112.47 },
            { x = 16, y = 80 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 409,
          name = "First Walljump",
          type = "Hitbox",
          shape = "polygon",
          x = 1640.83,
          y = 1805.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 31.2841, y = -480 },
            { x = 191.284, y = -480 },
            { x = 207.284, y = -464 },
            { x = 207.369, y = -656.47 },
            { x = 191.369, y = -672.47 },
            { x = 431.369, y = -672.47 },
            { x = 431.284, y = -448 },
            { x = 111.284, y = -448 },
            { x = 111.284, y = 112 },
            { x = -400.716, y = 112 },
            { x = -400.716, y = -16 },
            { x = -352.716, y = -16 },
            { x = -352.716, y = 48 },
            { x = 79.2841, y = 48 },
            { x = 79.2841, y = 16 },
            { x = 79.2841, y = -303.776 },
            { x = 71.448, y = -320 },
            { x = 63.2841, y = -303.776 },
            { x = 63.2841, y = 32 },
            { x = -336.716, y = 32 },
            { x = -336.716, y = 0 },
            { x = -320.716, y = 0 },
            { x = 31.2841, y = 0 }
          },
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1656.83,
          y = 1677.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 47.2841, y = -175.671 },
            { x = 47.2841, y = 160 },
            { x = -352.716, y = 160 },
            { x = -352.716, y = 128 },
            { x = -336.716, y = 128 },
            { x = -336.716, y = 80 },
            { x = -352.716, y = 80 },
            { x = -384.716, y = 96 },
            { x = -416.716, y = 96 },
            { x = -416.716, y = 112 },
            { x = -368.716, y = 112 },
            { x = -368.716, y = 176 },
            { x = 63.2841, y = 176 },
            { x = 63.2841, y = -175.671 },
            { x = 55.8999, y = -192 }
          },
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1304.83,
          y = 1749.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -8 },
            { x = -32, y = -24 },
            { x = -64, y = -24 },
            { x = -64, y = -40 },
            { x = -0.63091, y = -40.4704 },
            { x = -0.63091, y = -392.47 },
            { x = 15.3691, y = -392.47 },
            { x = 16, y = -40 },
            { x = 16, y = -8 }
          },
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 1240.83,
          y = 1725.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 64, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 32 },
            { x = 64, y = 32 },
            { x = 32, y = 48 },
            { x = 0, y = 48 }
          },
          properties = {
            ["axis_x"] = 1,
            ["render_priority"] = -10
          }
        },
        {
          id = 414,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1288.83,
          y = 1709.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 15.3691, y = -0.470433 },
            { x = -48.7159, y = 0 },
            { x = -48, y = -512 },
            { x = 32, y = -512 },
            { x = 31.3691, y = -352.47 },
            { x = 15.3691, y = -352.47 }
          },
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1693.85,
          y = 1149.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -5.65047, y = 47.5296 },
            { x = -21.6505, y = 31.5296 },
            { x = -21.0191, y = -304 },
            { x = -277.019, y = -304 },
            { x = -277.019, y = -336 },
            { x = 0, y = -336 }
          },
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1688.2,
          y = 1212.77,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -16 },
            { x = -31.3691, y = -15.53 },
            { x = -31.3691, y = -31.53 },
            { x = -95.3691, y = -95.53 },
            { x = -303.369, y = -95.53 },
            { x = -367.369, y = -31.53 },
            { x = -367.369, y = -15.53 },
            { x = -447.369, y = -15.53 },
            { x = -447.369, y = -367.53 },
            { x = -272, y = -368 },
            { x = -16, y = -368 },
            { x = -16, y = -32 }
          },
          properties = {}
        },
        {
          id = 419,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 1352.83,
          y = 1229.24,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "Platform 01",
          type = "Hitbox",
          shape = "polygon",
          x = -1575.17,
          y = -658.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = 96, y = 16 },
            { x = 96, y = 208 },
            { x = 2957.9, y = 208 },
            { x = 2960, y = -368 },
            { x = 2928, y = -400 },
            { x = 3136, y = -400 },
            { x = 3136, y = 208 },
            { x = 3136, y = 240 },
            { x = 0, y = 240 }
          },
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2280.83,
          y = 429.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 534,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2088.83,
          y = 269.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 112 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2280.83,
          y = 125.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 128 },
            { x = 16, y = 112 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2088.83,
          y = -50.7577,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -16, y = 112 },
            { x = 0, y = 128 }
          },
          properties = {}
        },
        {
          id = 539,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2280.83,
          y = 653.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 64 },
            { x = -384, y = 64 },
            { x = -384, y = 0 }
          },
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2664.83,
          y = -50.7577,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = -384, y = 16 },
            { x = -384, y = 0 }
          },
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 653.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 637.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 543,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 621.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 605.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 589.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 573.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 557.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 541.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 525.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 509.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 493.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 477.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 553,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 461.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 554,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 445.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 555,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 429.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 556,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 413.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 557,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 397.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 558,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 381.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 559,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 365.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 560,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 349.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 561,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 333.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 562,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 317.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 563,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 301.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 564,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 285.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 565,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 269.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 566,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 253.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 567,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1768.83,
          y = 237.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 568,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 1768.83,
          y = 221.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 571,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1656.83,
          y = 381.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 80 },
            { x = 16, y = 64 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 573,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1656.83,
          y = 205.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -128 },
            { x = 0, y = -48 },
            { x = 16, y = -64 },
            { x = 16, y = -112 }
          },
          properties = {}
        },
        {
          id = 574,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 1656.83,
          y = 541.242,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 112 },
            { x = -48, y = 112 },
            { x = -32, y = 128 },
            { x = 16, y = 128 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 575,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2720,
          y = 3024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -608 },
            { x = 0, y = 528 },
            { x = -16, y = 544 },
            { x = -32, y = 544 },
            { x = -32, y = -576 }
          },
          properties = {}
        },
        {
          id = 576,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2768,
          y = 3024,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -608 },
            { x = 32, y = -576 },
            { x = 32, y = 544 },
            { x = 16, y = 544 },
            { x = 0, y = 528 }
          },
          properties = {}
        },
        {
          id = 577,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2720,
          y = 3552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -16, y = 16 },
            { x = -144, y = 16 },
            { x = -144, y = 48 },
            { x = -64, y = 48 },
            { x = -48, y = 64 },
            { x = 0, y = 64 }
          },
          properties = {}
        },
        {
          id = 578,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2768,
          y = 3552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 96 },
            { x = -16, y = 112 },
            { x = -48, y = 112 },
            { x = -48, y = 144 },
            { x = 32, y = 144 },
            { x = 32, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 579,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2720,
          y = 3664,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = -208, y = 32 },
            { x = -208, y = 0 }
          },
          properties = {}
        },
        {
          id = 580,
          name = "Chimney",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2720,
          y = 2448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = -32, y = -160 },
            { x = 256, y = -160 },
            { x = 256, y = -128 },
            { x = 32, y = -128 },
            { x = 0, y = -104 }
          },
          properties = {}
        },
        {
          id = 581,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 2768,
          y = 2448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = 64, y = -32 },
            { x = 80, y = -16 },
            { x = 80, y = 0 }
          },
          properties = {}
        },
        {
          id = 582,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 2832,
          y = 2416,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 144, y = 0 },
            { x = 144, y = 32 },
            { x = 16, y = 32 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 583,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 2720,
          y = 2448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = -32 },
            { x = 48, y = -32 },
            { x = 48, y = 1104 },
            { x = 0, y = 1104 }
          },
          properties = {
            ["axis_y"] = -1,
            ["render_priority"] = -1,
            ["velocity"] = 0.25
          }
        },
        {
          id = 584,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -1255.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 64, y = 16 },
            { x = 224, y = 16 },
            { x = 240, y = 0 }
          },
          properties = {}
        },
        {
          id = 585,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -839.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 64, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 0 }
          },
          properties = {}
        },
        {
          id = 586,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -567.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 224, y = 16 },
            { x = 304, y = 16 },
            { x = 320, y = 0 }
          },
          properties = {}
        },
        {
          id = 587,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1463.17,
          y = -562.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -12.9854, y = -79.3197 },
            { x = 7.17, y = -79.3197 },
            { x = 144, y = 80 },
            { x = 2816, y = 80 },
            { x = 2816, y = -432 },
            { x = 2769.36, y = -479.677 },
            { x = 2768, y = -496 },
            { x = 2816, y = -496 },
            { x = 2848, y = -464 },
            { x = 2848, y = 112 },
            { x = -15.3074, y = 110.615 }
          },
          properties = {}
        },
        {
          id = 590,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1015.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = -192, y = 32 },
            { x = -192, y = 0 },
            { x = -176, y = 16 },
            { x = -16, y = 16 }
          },
          properties = {}
        },
        {
          id = 591,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -791.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 240, y = 32 },
            { x = 240, y = 0 },
            { x = 224, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 592,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -359.17,
          y = -690.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 112, y = 32 },
            { x = 112, y = 0 },
            { x = 96, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 593,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -327.17,
          y = -786.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 208, y = 0 },
            { x = 224, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 0 }
          },
          properties = {}
        },
        {
          id = 594,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -119.17,
          y = -786.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 80, y = 32 },
            { x = 80, y = 0 },
            { x = 64, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 596,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -103.17,
          y = -850.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 176, y = -16 },
            { x = 176, y = 32 },
            { x = 208, y = 32 },
            { x = 224, y = 16 },
            { x = 640, y = 16 },
            { x = 752, y = 16 },
            { x = 768, y = 32 },
            { x = 784, y = 32 },
            { x = 784, y = -256 },
            { x = 640, y = -256 },
            { x = 640, y = -176 },
            { x = 544, y = -96 },
            { x = 544, y = 0 },
            { x = 224, y = 0 },
            { x = 210.274, y = -16 }
          },
          properties = {}
        },
        {
          id = 597,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 104.83,
          y = -850.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 32 },
            { x = 560, y = 32 },
            { x = 544, y = 16 },
            { x = 16, y = 16 }
          },
          properties = {}
        },
        {
          id = 599,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -1255.17,
          y = -514.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 48, y = 0 },
            { x = 48, y = 32 },
            { x = 2608, y = 32 },
            { x = 2608, y = 0 }
          },
          properties = {
            ["axis_x"] = -1,
            ["velocity"] = 1.5
          }
        },
        {
          id = 601,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -215.17,
          y = -994.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 96, y = 32 },
            { x = 112, y = 16 },
            { x = 272, y = 16 },
            { x = 288, y = 32 },
            { x = 288, y = 0 },
            { x = 128, y = 0 },
            { x = 112, y = -16 },
            { x = 96, y = -16 }
          },
          properties = {}
        },
        {
          id = 602,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 296.83,
          y = -1042.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 176, y = -80 },
            { x = 240, y = -48 },
            { x = 240, y = -64 },
            { x = 384, y = -64 },
            { x = 384, y = -48 },
            { x = 448, y = -80 },
            { x = 400, y = -80 },
            { x = 384, y = -96 },
            { x = 240, y = -96 },
            { x = 224, y = -80 }
          },
          properties = {}
        },
        {
          id = 603,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = 712.83,
          y = -1058.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 0 },
            { x = 128, y = 48 },
            { x = 576, y = 48 },
            { x = 576, y = 0 }
          },
          properties = {
            ["axis_y"] = -1,
            ["render_priority"] = -200
          }
        },
        {
          id = 604,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 920.83,
          y = -1090.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 144 },
            { x = 144, y = 160 },
            { x = 160, y = 144 },
            { x = 159.608, y = 27.6825 },
            { x = 127.608, y = 27.6825 }
          },
          properties = {}
        },
        {
          id = 608,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 120.83,
          y = -1042.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 128, y = 32 },
            { x = 224, y = 32 },
            { x = 208, y = 16 },
            { x = 144, y = 16 }
          },
          properties = {}
        },
        {
          id = 609,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -87.17,
          y = -1042.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 336, y = 0 },
            { x = 336, y = 32 },
            { x = 352, y = 16 },
            { x = 416, y = 16 },
            { x = 432, y = 32 },
            { x = 432, y = -48 }
          },
          properties = {}
        },
        {
          id = 611,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 680.83,
          y = -1138.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 16 },
            { x = 80, y = 16 },
            { x = 80, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 612,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 312.83,
          y = -1138.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 144, y = 16 },
            { x = 208, y = 16 },
            { x = 224, y = 0 },
            { x = 144, y = 0 }
          },
          properties = {}
        },
        {
          id = 614,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -119.17,
          y = -962.758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 192, y = 0 },
            { x = 176, y = -16 },
            { x = 16, y = -16 }
          },
          properties = {}
        },
        {
          id = 615,
          name = "",
          type = "",
          shape = "polygon",
          x = -1540.96,
          y = 719.222,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1.868, y = -2.40305 },
            { x = 318.132, y = -2.40305 },
            { x = 318.132, y = -450.403 },
            { x = 366.132, y = -450.403 },
            { x = 366.132, y = -2.40305 },
            { x = 916.648, y = -0.264626 },
            { x = 916.648, y = -656.265 },
            { x = 1044.96, y = -656.265 },
            { x = 1044.96, y = -0.264626 },
            { x = 1476.96, y = -0.264626 },
            { x = 1476.96, y = 95.7354 },
            { x = -1.868, y = 93.5969 }
          },
          properties = {}
        },
        {
          id = 616,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1254.83,
          y = 716.819,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = -16 },
            { x = 16, y = -447.365 },
            { x = 32, y = -464 },
            { x = 80, y = -464 },
            { x = 96, y = -448 },
            { x = 96, y = -16 },
            { x = 112, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = -448 },
            { x = 32, y = -448 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 617,
          name = "",
          type = "MovableHitbox",
          shape = "polygon",
          x = -1935.92,
          y = -502.348,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 48 },
            { x = 48, y = 48 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 618,
          name = "From",
          type = "Path",
          shape = "point",
          x = -1912.69,
          y = -413.538,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["next"] = { id = 619 },
            ["target"] = { id = 617 }
          }
        },
        {
          id = 619,
          name = "To",
          type = "PathNode",
          shape = "point",
          x = -1911.96,
          y = -558.742,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 620,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -1286.83,
          y = 620.819,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = 0 },
            { x = -48, y = -80 },
            { x = -24.1008, y = -120.168 },
            { x = 0, y = -80 }
          },
          properties = {
            ["axis_y"] = -1
          }
        },
        {
          id = 626,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -816,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = 0 },
            { x = -48, y = -87.832 },
            { x = -24.1008, y = -128 },
            { x = 0, y = -87.832 }
          },
          properties = {
            ["axis_y"] = -1
          }
        },
        {
          id = 627,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -768,
          y = 672,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -48, y = 0 },
            { x = -48.3416, y = -183.409 },
            { x = -24.4424, y = -223.577 },
            { x = -0.341642, y = -183.409 }
          },
          properties = {
            ["axis_y"] = -1
          }
        },
        {
          id = 629,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -880.313,
          y = 30.9577,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 224, y = 0 },
            { x = 224, y = -112 },
            { x = -128, y = -112 },
            { x = -128, y = 0 }
          },
          properties = {
            ["axis_x"] = 1
          }
        },
        {
          id = 630,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -624.313,
          y = 62.9577,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 656 },
            { x = -16, y = 656 },
            { x = -16, y = 0 },
            { x = -30.6349, y = -16.3468 },
            { x = -64, y = -17.1374 },
            { x = -64, y = -32 },
            { x = -16, y = -32 },
            { x = 0, y = -16 },
            { x = 128.313, y = -16 },
            { x = 144.313, y = 0 },
            { x = 144.313, y = 656 },
            { x = 128.313, y = 656 },
            { x = 128.313, y = 0 }
          },
          properties = {}
        },
        {
          id = 633,
          name = "",
          type = "BoostField",
          shape = "polygon",
          x = -400.313,
          y = 78.9577,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -79.6871, y = 0 },
            { x = -79.3742, y = 49.0423 },
            { x = 320.626, y = 49.0423 },
            { x = 320.313, y = 0 }
          },
          properties = {
            ["axis_y"] = -1
          }
        },
        {
          id = 635,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1024.31,
          y = -81.0423,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -527.687, y = 1.04229 },
            { x = 529.372, y = 1.04229 },
            { x = 544.626, y = 17.0423 },
            { x = 688.626, y = 17.0423 },
            { x = 736.626, y = 49.0423 },
            { x = 784.626, y = 17.0423 },
            { x = 896.626, y = 17.0423 },
            { x = 944.626, y = 49.0423 },
            { x = 944.313, y = 736 },
            { x = 960.626, y = 737.042 },
            { x = 960.626, y = -14.9577 },
            { x = -527.687, y = -14.9577 }
          },
          properties = {}
        },
        {
          id = 637,
          name = "Boost Field 01",
          type = "",
          shape = "polygon",
          x = -1552,
          y = -96,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 1488.31, y = 0 },
            { x = 1488.31, y = 752 },
            { x = 1568.31, y = 752 },
            { x = 1568.31, y = -80 },
            { x = 0, y = -80 }
          },
          properties = {}
        },
        {
          id = 638,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = -112,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 643,
          name = "Bridge",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -1329.41,
          y = 1295.1,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 32 },
            { x = 1184, y = 32 },
            { x = 1184, y = 0 }
          },
          properties = {}
        },
        {
          id = 655,
          name = "Recorder",
          type = "PlayerRecorderPlayback",
          shape = "point",
          x = -959.167,
          y = 1782.84,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["path"] = "test.csv"
          }
        },
        {
          id = 662,
          name = "",
          type = "",
          shape = "polygon",
          x = -1296,
          y = 1328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 496 },
            { x = 48, y = 496 },
            { x = 48, y = 32 },
            { x = 193.817, y = 32 },
            { x = 48, y = 128 },
            { x = 48, y = 160 },
            { x = 240, y = 32 },
            { x = 368, y = 32 },
            { x = 416, y = 0 },
            { x = 384, y = 0 }
          },
          properties = {}
        },
        {
          id = 663,
          name = "",
          type = "",
          shape = "polygon",
          x = -176,
          y = 1328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 496 },
            { x = -48, y = 496 },
            { x = -48, y = 32 },
            { x = -193.817, y = 32 },
            { x = -48, y = 128 },
            { x = -48, y = 160 },
            { x = -240, y = 32 },
            { x = -368, y = 32 },
            { x = -416, y = 0 }
          },
          properties = {}
        },
        {
          id = 670,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -400,
          y = 2512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -16, y = -144 },
            { x = 96, y = -144 },
            { x = 112, y = -160 },
            { x = 112, y = 48 },
            { x = 121.68, y = 105.548 },
            { x = 141.433, y = 153.284 },
            { x = 165.333, y = 196 },
            { x = 208, y = 244 },
            { x = 254.667, y = 285.333 },
            { x = 305.509, y = 314.589 },
            { x = 368, y = 336 },
            { x = 418.101, y = 350.675 },
            { x = 481.707, y = 360.053 },
            { x = 538.273, y = 365.462 },
            { x = 592, y = 368 },
            { x = 592, y = 480 },
            { x = 544, y = 416 },
            { x = -16, y = 416 }
          },
          properties = {}
        },
        {
          id = 673,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 784,
          y = 2512,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 16, y = -144 },
            { x = -96, y = -144 },
            { x = -112, y = -160 },
            { x = -112, y = 48 },
            { x = -121.68, y = 105.548 },
            { x = -141.433, y = 153.284 },
            { x = -165.333, y = 196 },
            { x = -208, y = 244 },
            { x = -254.667, y = 285.333 },
            { x = -305.509, y = 314.589 },
            { x = -368, y = 336 },
            { x = -418.101, y = 350.675 },
            { x = -481.707, y = 360.053 },
            { x = -538.273, y = 365.462 },
            { x = -592, y = 368 },
            { x = -592, y = 480 },
            { x = -544, y = 416 },
            { x = 16, y = 416 }
          },
          properties = {}
        },
        {
          id = 686,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -288,
          y = 2336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 16 },
            { x = -16, y = 32 },
            { x = -128, y = 32 },
            { x = -128, y = 592 },
            { x = 432, y = 592 },
            { x = 480, y = 656 },
            { x = 528, y = 592 },
            { x = 1088, y = 592 },
            { x = 1088, y = 32 },
            { x = 976, y = 32 },
            { x = 960, y = 16 },
            { x = 1312, y = 16 },
            { x = 1312, y = 832 },
            { x = -128, y = 832 },
            { x = -368, y = 832 },
            { x = -368, y = 16 }
          },
          properties = {}
        },
        {
          id = 690,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = -288,
          y = 2272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -128, y = 0 },
            { x = -128, y = -16 },
            { x = -16, y = -16 }
          },
          properties = {}
        },
        {
          id = 691,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = -288,
          y = 2272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -224 },
            { x = 1008, y = -224 },
            { x = 1008, y = -304 },
            { x = -128, y = -304 },
            { x = -128, y = -16 },
            { x = -16, y = -16 }
          },
          properties = {}
        },
        {
          id = 692,
          name = "",
          type = "Wall",
          shape = "polygon",
          x = -416,
          y = 1968,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 1120 },
            { x = 1216, y = 1120 },
            { x = 1216, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 610,
          name = "NPC",
          type = "NPC",
          shape = "point",
          x = 512,
          y = -880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "slippery_floor_tutorial",
            ["should_focus"] = false,
            ["type"] = "eyes"
          }
        },
        {
          id = 613,
          name = "Coin",
          type = "Coin",
          shape = "point",
          x = 512,
          y = -1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 639,
          name = "NPC",
          type = "NPC",
          shape = "point",
          x = -24.119,
          y = -1019.7,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["dialog_id"] = "slippery_floor_tutorial",
            ["should_focus"] = false,
            ["type"] = "ghost"
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
