return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 32,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 265,
  properties = {},
  tilesets = {
    {
      name = "debug_tileset_objects",
      firstgid = 1,
      filename = "../tilesets/debug_tileset_objects.tsx",
      exportfilename = "../tilesets/debug_tileset_objects.lua"
    },
    {
      name = "debug_tileset",
      firstgid = 7,
      filename = "../tilesets/debug_tileset.tsx",
      exportfilename = "../tilesets/debug_tileset.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../tilesets/debug_tileset_16x16/tile.png",
      id = 3,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = true,
      repeaty = true,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aux",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "back",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "hitbox",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 260,
          name = "Spawn",
          type = "PlayerSpawn",
          shape = "point",
          x = 72.148,
          y = -622.405,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "Hitbox",
          shape = "polygon",
          x = 336,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -240, y = 0 },
            { x = -240, y = 64 },
            { x = 208, y = 64 },
            { x = 208, y = -240 },
            { x = 128, y = -240 },
            { x = 144, y = -224 },
            { x = 144, y = 0 },
            { x = 80, y = 0 },
            { x = 80, y = 16 },
            { x = -16, y = 16 },
            { x = -16, y = 0 },
            { x = -96, y = 0 },
            { x = -96, y = 16 },
            { x = -192, y = 16 },
            { x = -192, y = 0 },
            { x = -240, y = 0 }
          },
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 176,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = -16 },
            { x = 64, y = -16 },
            { x = 64, y = 16 },
            { x = -32, y = 16 }
          },
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "BouncePad",
          shape = "polygon",
          x = 352,
          y = -592,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -32, y = 0 },
            { x = -32, y = 32 },
            { x = 64, y = 32 },
            { x = 64, y = 0 }
          },
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "SlipperyHitbox",
          shape = "polygon",
          x = 464,
          y = -576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -224 },
            { x = 0, y = -240 },
            { x = 16, y = -224 },
            { x = 16, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "front",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 32,
      id = 4,
      name = "noop",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      chunks = {}
    }
  }
}
